name: 'Build and Push Docker Images'
description: 'Build and push backend and frontend Docker images to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Base image name'
    required: false
    default: '${{ github.repository }}'
  environment:
    description: 'Environment name (test, integration, etc.)'
    required: true
  version:
    description: 'Version identifier for tagging (tag name or short SHA)'
    required: true
  github-token:
    description: 'GitHub token for registry login'
    required: true
  sentry-auth-token:
    description: 'Sentry auth token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=${{ inputs.version }}

    - name: Save image tag and normalize repository name
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
        # Convertir le nom du repository en minuscules pour Docker
        NORMALIZED_REPO=$(echo "${{ inputs.image-name }}" | tr '[:upper:]' '[:lower:]')
        echo "NORMALIZED_REPO=${NORMALIZED_REPO}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check worker version is not already created
      shell: bash
      id: check-image-worker
      run: |
        if docker manifest inspect ${{ env.IMAGE_TAG }}-worker > /dev/null 2>&1; then
          echo "worker-exists=true" >> $GITHUB_OUTPUT
        else
          echo "worker-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker worker image
      if: steps.check-image-worker.outputs.worker-exists == 'false'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/backend/Dockerfile.worker
        push: true
        tags: ${{ env.IMAGE_TAG }}-worker
        labels: ${{ steps.meta.outputs.labels }}
        secrets: |
          SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }}
        cache-from: |
          type=gha,scope=worker
        cache-to: |
          type=gha,mode=max,scope=worker
        platforms: linux/amd64

    - name: Check backend version is not already created
      shell: bash
      id: check-image-backend
      run: |
        if docker manifest inspect ${{ env.IMAGE_TAG }}-backend > /dev/null 2>&1; then
          echo "backend-exists=true" >> $GITHUB_OUTPUT
        else
          echo "backend-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker backend image
      if: steps.check-image-backend.outputs.backend-exists == 'false'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/backend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}-backend
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          APP_VERSION=${{ inputs.version }}
        secrets: |
          SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }}
        cache-from: |
          type=gha,scope=backend
        cache-to: |
          type=gha,mode=max,scope=backend
        platforms: linux/amd64

    - name: Check frontend version is not already created
      shell: bash
      id: check-image-frontend
      run: |
        if docker manifest inspect ${{ env.IMAGE_TAG }}-frontend-${{ inputs.environment }} > /dev/null 2>&1; then
          echo "frontend-exists=true" >> $GITHUB_OUTPUT
        else
          echo "frontend-exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker frontend image
      if: steps.check-image-frontend.outputs.frontend-exists == 'false'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/frontend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}-frontend-${{ inputs.environment }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VITE_IS_LOGGED_TOKEN_NAME=is_logged_token
          SENTRY_ENABLED=true
          SENTRY_ENVIRONEMENT=${{ inputs.environment }}
          APP_VERSION=${{ inputs.version }}
          SENTRY_DSN_FRONTEND=https://343eb82fc1395b23dc747ac7d2fac3d6@sentry2.fabrique.social.gouv.fr/49
          VITE_MATOMO_URL=https://matomo.fabrique.social.gouv.fr/
          VITE_MATOMO_SITE_ID=${{ inputs.environment == 'production' && '154' || '155' }}
        secrets: |
          SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }}
        cache-from: |
          type=gha,scope=frontend
        cache-to: |
          type=gha,mode=max,scope=frontend
        platforms: linux/amd64
