name: 'Build and Push Docker Images'
description: 'Build and push backend and frontend Docker images to GitHub Container Registry'

inputs:
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Base image name'
    required: false
    default: '${{ github.repository }}'
  environment:
    description: 'Environment name (test, integration, etc.)'
    required: true
  version:
    description: 'Version identifier for tagging (tag name or short SHA)'
    required: true
  github-token:
    description: 'GitHub token for registry login'
    required: true
  sentry-auth-token:
    description: 'Sentry auth token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug Sentry tokens
      shell: bash
      run: |
        echo "=== Debug Sentry Tokens ==="
        echo "Backend token length: ${#SENTRY_AUTH_TOKEN}"
        echo "Backend token first 5 chars: ${SENTRY_AUTH_TOKEN:0:5}"
        echo "Backend token last 5 chars: ${SENTRY_AUTH_TOKEN: -5}"
        echo "=========================="
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentry-auth-token }}

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=raw,value=${{ inputs.version }}

    - name: Save image tag and normalize repository name
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
        # Convertir le nom du repository en minuscules pour Docker
        NORMALIZED_REPO=$(echo "${{ inputs.image-name }}" | tr '[:upper:]' '[:lower:]')
        echo "NORMALIZED_REPO=${NORMALIZED_REPO}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/backend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}-backend
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          APP_VERSION=${{ inputs.version }}
        secrets: |
          SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }}
        cache-from: |
          type=gha,scope=backend
        cache-to: |
          type=gha,mode=max,scope=backend
        platforms: linux/amd64

    - name: Build and push Docker frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/frontend/Dockerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}-frontend
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VITE_IS_LOGGED_TOKEN_NAME=is_logged_token
          SENTRY_ENABLED=true
          SENTRY_ENVIRONEMENT=${{ inputs.environment }}
          APP_VERSION=${{ inputs.version }}
          SENTRY_DSN_FRONTEND=https://343eb82fc1395b23dc747ac7d2fac3d6@sentry2.fabrique.social.gouv.fr/49
        secrets: |
          SENTRY_AUTH_TOKEN=${{ inputs.sentry-auth-token }}
        cache-from: |
          type=gha,scope=frontend
        cache-to: |
          type=gha,mode=max,scope=frontend
        platforms: linux/amd64 