packages:
  - packages/*
  - apps/*
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@sentry/cli": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
catalog:
  "@biomejs/biome": ^2.4.12
  "@codegouvfr/react-dsfr": ^1.32.0
  "@types/node": ^25.6.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitest/browser": ^4.1.4
  "@vitest/coverage-v8": ^4.1.5
  hono: ^4.12.14
  hono-openapi: ^1.3.0
  prisma: ^7.8.0
  react: ^19.2.5
  react-dom: ^19.2.5
  tsx: ^4.21.0
  vitest: ^4.1.5
  zod: ^4.3.6
enablePrePostScripts: true
minimumReleaseAge: 0
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  uuid@<14.0.0: '>=14.0.0'
