packages:
  - packages/*
  - apps/*
catalog:
  prisma: ^6.13.0
  tsx: ^4.21.0
  zod: ^4.3.6
  react: ^19.2.3
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@types/node": ^24.10.1
  react-dom: ^19.2.3
  "@codegouvfr/react-dsfr": ^1.31.0
  hono: ^4.11.5
  hono-openapi: ^1.1.2
  "@biomejs/biome": ^2.3.12
  vitest: ^4.0.18
  "@vitest/coverage-v8": ^4.0.17
  "@vitest/browser": ^4.0.17
onlyBuiltDependencies:
  - "@prisma/client"
