packages:
  - packages/*
  - apps/*
catalog:
    prisma: ^6.11.1
    zod: ^3.25.67
    react: ^19.1.0
    react-dom: ^19.1.0
    "@codegouvfr/react-dsfr": ^1.25.3
    hono: ^4.8.3
    hono-openapi: ^0.4.8
    '@biomejs/biome': ^2.1.1
    vitest: ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/browser': ^3.2.4
onlyBuiltDependencies:
  - '@prisma/client'
