packages:
  - packages/*
  - apps/*
catalog:
    prisma: ^6.10.1
    zod: ^3.25.67
    react: ^19.1.0
    react-dom: ^19.1.0
    "@codegouvfr/react-dsfr": ^1.25.3
    hono: "^4.8.3"
onlyBuiltDependencies:
  - '@prisma/client'
