packages:
  - packages/*
  - apps/*
catalog:
  prisma: ^6.13.0
  tsx: ^4.21.0
  zod: ^4.3.6
  react: ^19.2.4
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/node": ^24.10.1
  react-dom: ^19.2.4
  "@codegouvfr/react-dsfr": ^1.31.1
  hono: ^4.11.9
  hono-openapi: ^1.2.0
  "@biomejs/biome": ^2.4.2
  vitest: ^4.0.18
  "@vitest/coverage-v8": ^4.0.17
  "@vitest/browser": ^4.0.17
onlyBuiltDependencies:
  - "@prisma/client"
