packages:
  - packages/*
  - apps/*
catalogs:
  prisma:
    prisma: latest
  zod:
    zod: 3.24.2,
  react:
    react: 19.0.0,
  react-dsfr:
    "@codegouvfr/react-dsfr": 1.22.5
  hono:
    hono: 4.8.1,
onlyBuiltDependencies:
  - '@prisma/client'
