/**
 * diff-entites.ts
 *
 * Compares a CSV file against the Entite table and emits INSERT/UPDATE SQL.
 * No DELETE is ever generated.
 *
 * Usage:
 *   tsx src/scripts/diff-entites.ts --csv <path> [--dump-migration] [--invert]
 *
 * Modes:
 *   (default)          Analyze mode: prints INSERT/UPDATE/SKIP/WARN counts to stdout.
 *   --dump-migration   Dump mode: emits SQL to stdout (pipe to migration.sql).
 *   --invert           Combined with --dump-migration: emits rollback SQL.
 *                      UPDATEs are reverted using values read from DB at diff time.
 *                      INSERTs are NOT reversible (id is generated by pg at runtime);
 *                      a SQL comment is emitted instead.
 *
 * CSV format:
 *   Semicolon-separated, UTF-8 (BOM optional). Headers must match exactly (case-insensitive,
 *   diacritics-insensitive). Template: prisma/documents/entites_template.csv
 *
 *   - id empty      → INSERT (gen_random_uuid())
 *   - id present    → lookup in DB → UPDATE if diff, SKIP if identical, WARN if not found
 *
 * Developer workflow:
 *   1. pnpm op:diff:entites:analyze          # verify counts and warnings
 *   2. pnpm op:diff:entites:up               # generates migration.sql
 *   3. pnpm db:migrate --name <name>         # Prisma creates migration file
 *      # paste migration.sql content into the generated .sql file
 *   4. pnpm db:deploy                        # apply
 *
 * Rollback:
 *   pnpm op:diff:entites:down                # generates down.sql
 *   pnpm db:execute --file apps/backend/down.sql
 */

import fs from 'node:fs';
import path from 'node:path';
import { prisma } from '../libs/prisma.js';

type CsvRow = {
  id: string; // empty = INSERT, non-empty = UPDATE candidate
  nomComplet: string | undefined;
  label: string | undefined;
  isActive: boolean | undefined;
  email: string | undefined;
  emailContactUsager: string | undefined;
  telContactUsager: string | undefined;
  adresseContactUsager: string | undefined;
  emailDomain: string | undefined;
  organizationalUnit: string | undefined;
  entiteTypeId: string | undefined;
  entiteMereId: string | null | undefined; // undefined = not provided (skip), null = explicitly empty
};

type DbRow = {
  id: string;
  nomComplet: string;
  label: string;
  isActive: boolean;
  email: string;
  emailContactUsager: string;
  telContactUsager: string;
  adresseContactUsager: string;
  emailDomain: string;
  organizationalUnit: string;
  entiteTypeId: string;
  entiteMereId: string | null;
};

const args = process.argv.slice(2);
const isDumpMigration = args.includes('--dump-migration');
const isInvert = args.includes('--invert');

const csvArgIndex = args.indexOf('--csv');
if (csvArgIndex === -1 || !args[csvArgIndex + 1]) {
  console.error('Usage: tsx src/scripts/diff-entites.ts --csv <path> [--dump-migration] [--invert]');
  process.exit(1);
}
const csvPath = args[csvArgIndex + 1];

// -------------------------
// Helpers: sql escaping
// -------------------------
function escapeSql(val: unknown): string {
  if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'boolean') return val ? 'true' : 'false';
  return String(val);
}

function stripBom(s: string) {
  return s.charCodeAt(0) === 0xfeff ? s.slice(1) : s;
}

// -------------------------
// CSV parser (;) with quotes
// -------------------------
function parseCsv(content: string, delimiter = ';'): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let cell = '';
  let inQuotes = false;

  for (let i = 0; i < content.length; i++) {
    const c = content[i];

    if (c === '"') {
      if (inQuotes && content[i + 1] === '"') {
        cell += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (!inQuotes && c === delimiter) {
      row.push(cell);
      cell = '';
      continue;
    }

    if (!inQuotes && (c === '\n' || c === '\r')) {
      if (c === '\r' && content[i + 1] === '\n') i++;
      row.push(cell);
      rows.push(row);
      row = [];
      cell = '';
      continue;
    }

    cell += c;
  }

  row.push(cell);
  rows.push(row);

  if (rows.length && rows[rows.length - 1].every((x) => x.trim() === '')) rows.pop();
  return rows;
}

// -------------------------
// Header helpers
// -------------------------
function normHeader(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/\s+/g, ' ');
}

function findHeaderIndex(headers: string[], expected: string): number {
  const target = normHeader(expected);
  return headers.findIndex((h) => normHeader(h) === target);
}

// -------------------------
// Parse isActive cell
// -------------------------
function parseBoolean(raw: string): boolean {
  const v = raw.trim().toLowerCase();
  return v === 'true' || v === '1' || v === 'oui';
}

// -------------------------
// CSV -> rows
// -------------------------
function mapCsvToRows(csvFileContent: string): { inserts: CsvRow[]; updates: CsvRow[]; warnings: string[] } {
  const raw = stripBom(csvFileContent);
  const table = parseCsv(raw, ';');
  if (table.length < 2) throw new Error('CSV is empty or has no data rows');

  const headers = table[0].map((h) => h.trim());
  const data = table.slice(1);

  const idxId = findHeaderIndex(headers, 'id');
  const idxNomComplet = findHeaderIndex(headers, 'nomComplet');
  const idxLabel = findHeaderIndex(headers, 'label');
  const idxIsActive = findHeaderIndex(headers, 'isActive');
  const idxEmail = findHeaderIndex(headers, 'email');
  const idxEmailContactUsager = findHeaderIndex(headers, 'emailContactUsager');
  const idxTelContactUsager = findHeaderIndex(headers, 'telContactUsager');
  const idxAdresseContactUsager = findHeaderIndex(headers, 'adresseContactUsager');
  const idxEmailDomain = findHeaderIndex(headers, 'emailDomain');
  const idxOrganizationalUnit = findHeaderIndex(headers, 'organizationalUnit');
  const idxEntiteTypeId = findHeaderIndex(headers, 'entiteTypeId');
  const idxEntiteMereId = findHeaderIndex(headers, 'entiteMereId');

  const requiredCols = [
    ['id', idxId],
    ['nomComplet', idxNomComplet],
    ['label', idxLabel],
    ['isActive', idxIsActive],
    ['entiteTypeId', idxEntiteTypeId],
  ] as const;

  for (const [name, idx] of requiredCols) {
    if (idx === -1) throw new Error(`Column "${name}" not found. Headers: ${headers.join(' | ')}`);
  }

  const inserts: CsvRow[] = [];
  const updates: CsvRow[] = [];
  const warnings: string[] = [];

  for (let i = 0; i < data.length; i++) {
    const line = data[i];
    const lineNum = i + 2;

    const id = (line[idxId] ?? '').trim();
    const nomComplet = (line[idxNomComplet] ?? '').trim() || undefined;
    const label = (line[idxLabel] ?? '').trim() || undefined;
    const isActiveRaw = (line[idxIsActive] ?? '').trim();
    const isActive = isActiveRaw ? parseBoolean(isActiveRaw) : undefined;
    const email = (line[idxEmail] ?? '').trim() || undefined;
    const emailContactUsager = (line[idxEmailContactUsager] ?? '').trim() || undefined;
    const telContactUsager = (line[idxTelContactUsager] ?? '').trim() || undefined;
    const adresseContactUsager = (line[idxAdresseContactUsager] ?? '').trim() || undefined;
    const emailDomain = (line[idxEmailDomain] ?? '').trim() || undefined;
    const organizationalUnit = (line[idxOrganizationalUnit] ?? '').trim() || undefined;
    const entiteTypeId = (line[idxEntiteTypeId] ?? '').trim() || undefined;
    const entiteMereIdRaw = idxEntiteMereId !== -1 ? (line[idxEntiteMereId] ?? '').trim() : '';
    const entiteMereId = entiteMereIdRaw ? entiteMereIdRaw : undefined;

    // skip fully empty lines
    if (!nomComplet && !label && !entiteTypeId && !id) continue;

    // For INSERT, required fields must be present
    if (!id) {
      if (!entiteTypeId) {
        warnings.push(`Line ${lineNum}: entiteTypeId missing — row skipped`);
        continue;
      }
      if (!nomComplet) {
        warnings.push(`Line ${lineNum}: nomComplet missing — row skipped`);
        continue;
      }
      if (!label) {
        warnings.push(`Line ${lineNum}: label missing — row skipped`);
        continue;
      }
    }

    const row: CsvRow = {
      id,
      nomComplet,
      label,
      isActive,
      email,
      emailContactUsager,
      telContactUsager,
      adresseContactUsager,
      emailDomain,
      organizationalUnit,
      entiteTypeId,
      entiteMereId,
    };

    if (!id) {
      inserts.push(row);
    } else {
      updates.push(row);
    }
  }

  return { inserts, updates, warnings };
}

// -------------------------
// Editable fields diff
// -------------------------
const EDITABLE_FIELDS = [
  'nomComplet',
  'label',
  'isActive',
  'email',
  'emailContactUsager',
  'telContactUsager',
  'adresseContactUsager',
  'emailDomain',
  'organizationalUnit',
  'entiteTypeId',
  'entiteMereId',
] as const;

type EditableField = (typeof EDITABLE_FIELDS)[number];

function hasDiff(db: DbRow, csv: CsvRow): boolean {
  for (const field of EDITABLE_FIELDS) {
    const csvVal = csv[field];
    if (csvVal === undefined) continue; // not provided in CSV, skip
    const dbVal = db[field] ?? null;
    if (String(dbVal) !== String(csvVal)) return true;
  }
  return false;
}

function buildSetClause(db: DbRow, csv: CsvRow): string {
  return EDITABLE_FIELDS.filter((f) => csv[f] !== undefined && String(db[f] ?? null) !== String(csv[f]))
    .map((f) => `"${f}" = ${escapeSql(csv[f])}`)
    .join(', ');
}

function buildSetClauseFromDb(row: DbRow): string {
  return EDITABLE_FIELDS.map((f) => `"${f}" = ${escapeSql(row[f as EditableField])}`).join(', ');
}

// -------------------------
// Main
// -------------------------
async function main() {
  const csvAbs = path.isAbsolute(csvPath) ? csvPath : path.join(process.cwd(), csvPath);
  const csvContent = fs.readFileSync(csvAbs, 'utf-8');

  const { inserts, updates: updateCandidates, warnings } = mapCsvToRows(csvContent);

  const csvIds = updateCandidates.map((r) => r.id);

  const dbRows = csvIds.length
    ? ((await prisma.entite.findMany({
        where: { id: { in: csvIds } },
        select: {
          id: true,
          nomComplet: true,
          label: true,
          isActive: true,
          email: true,
          emailContactUsager: true,
          telContactUsager: true,
          adresseContactUsager: true,
          emailDomain: true,
          organizationalUnit: true,
          entiteTypeId: true,
          entiteMereId: true,
        },
      })) as DbRow[])
    : [];

  const dbById = new Map(dbRows.map((r) => [r.id, r]));

  const toUpdate: Array<{ db: DbRow; csv: CsvRow }> = [];
  const skipped: CsvRow[] = [];
  const notFound: CsvRow[] = [];

  for (const csvRow of updateCandidates) {
    const db = dbById.get(csvRow.id);
    if (!db) {
      notFound.push(csvRow);
      continue;
    }
    if (hasDiff(db, csvRow)) {
      toUpdate.push({ db, csv: csvRow });
    } else {
      skipped.push(csvRow);
    }
  }

  if (!isDumpMigration) {
    console.log(`CSV: ${csvAbs}`);
    console.log(
      `INSERT: ${inserts.length}, UPDATE: ${toUpdate.length}, SKIP: ${skipped.length}, WARN(not found): ${notFound.length}`,
    );
    if (notFound.length) {
      console.log(`\n  IDs not found in DB (will be ignored):`);
      notFound.forEach((r) => {
        console.log(`  - ${r.id} (${r.nomComplet})`);
      });
    }
    if (warnings.length) {
      console.log(`\n  CSV warnings:`);
      warnings.forEach((w) => {
        console.log(`  - ${w}`);
      });
    }
    await prisma.$disconnect();
    return;
  }

  // ---- SQL dump ----

  if (isInvert) {
    if (inserts.length) {
      console.log(`-- [DOWN] Revert INSERTs — not reversible because id is auto-generated at execution time`);
      console.log(`-- The following rows were inserted without a known id upfront.`);
      console.log(`-- To delete them, find their ids in DB and run the DELETE statements manually.`);
      for (const r of inserts) {
        console.log(
          `-- INSERT not reversible: nomComplet=${escapeSql(r.nomComplet ?? '')} entiteTypeId=${escapeSql(r.entiteTypeId ?? '')}`,
        );
      }
    }

    if (toUpdate.length) {
      console.log(`\n-- [DOWN] Revert UPDATEs`);
      for (const { db } of toUpdate) {
        console.log(`UPDATE "public"."Entite" SET ${buildSetClauseFromDb(db)} WHERE "id" = ${escapeSql(db.id)};`);
      }
    }

    await prisma.$disconnect();
    return;
  }

  console.log(`-- CSV used: ${csvAbs}`);
  if (warnings.length) {
    console.log(`-- WARNINGS: ${warnings.length} (run without --dump-migration for details)`);
  }
  if (notFound.length) {
    console.log(`-- IDs not found in DB (ignored): ${notFound.map((r) => r.id).join(', ')}`);
  }

  if (inserts.length) {
    console.log(`\n-- INSERT`);
    console.log(
      `INSERT INTO "public"."Entite" ("id","nomComplet","label","isActive","email","emailContactUsager","telContactUsager","adresseContactUsager","emailDomain","organizationalUnit","entiteTypeId","entiteMereId") VALUES`,
    );
    const values = inserts
      .map(
        (r) =>
          `(gen_random_uuid(), ${escapeSql(r.nomComplet ?? '')}, ${escapeSql(r.label ?? '')}, ${escapeSql(r.isActive ?? false)}, ${escapeSql(r.email ?? '')}, ${escapeSql(r.emailContactUsager ?? '')}, ${escapeSql(r.telContactUsager ?? '')}, ${escapeSql(r.adresseContactUsager ?? '')}, ${escapeSql(r.emailDomain ?? '')}, ${escapeSql(r.organizationalUnit ?? '')}, ${escapeSql(r.entiteTypeId ?? '')}, ${escapeSql(r.entiteMereId ?? null)})`,
      )
      .join(',\n');
    console.log(`${values};`);
  }

  if (toUpdate.length) {
    console.log(`\n-- UPDATE`);
    for (const { db, csv } of toUpdate) {
      console.log(`UPDATE "public"."Entite" SET ${buildSetClause(db, csv)} WHERE "id" = ${escapeSql(csv.id)};`);
    }
  }

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
