import { EnvSchema } from './env.schema';

const processEnv = {
  // PC
  PC_DOMAIN: process.env.PC_DOMAIN,
  PC_CLIENT_ID: process.env.PC_CLIENT_ID,
  PC_CLIENT_SECRET: process.env.PC_CLIENT_SECRET,
  PC_ID_TOKEN_SIGNED_RESPONSE_ALG: process.env.PC_ID_TOKEN_SIGNED_RESPONSE_ALG,
  PC_USERINFO_SIGNED_RESPONSE_ALG: process.env.PC_USERINFO_SIGNED_RESPONSE_ALG,
  PC_REDIRECT_URI: process.env.PC_REDIRECT_URI,
  // Auth
  AUTH_TOKEN_NAME: process.env.AUTH_TOKEN_NAME,
  REFRESH_TOKEN_NAME: process.env.REFRESH_TOKEN_NAME,
  IS_LOGGED_TOKEN_NAME: process.env.IS_LOGGED_TOKEN_NAME,
  AUTH_TOKEN_EXPIRATION: process.env.AUTH_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION: process.env.REFRESH_TOKEN_EXPIRATION,
  AUTH_TOKEN_SECRET_KEY: process.env.AUTH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
  // Frontend
  FRONTEND_URI: process.env.FRONTEND_URI,
  FRONTEND_REDIRECT_URI: process.env.FRONTEND_REDIRECT_URI,
  FRONTEND_REDIRECT_LOGIN_URI: process.env.FRONTEND_REDIRECT_LOGIN_URI,
  // DematSocial
  DEMAT_SOCIAL_API_URL: process.env.DEMAT_SOCIAL_API_URL,
  DEMAT_SOCIAL_API_TOKEN: process.env.DEMAT_SOCIAL_API_TOKEN,
  DEMAT_SOCIAL_API_DIRECTORY: process.env.DEMAT_SOCIAL_API_DIRECTORY,
  // Internal
  LOG_FORMAT: process.env.LOG_FORMAT,
};

const validateEnvVars = () => EnvSchema.parse(processEnv);

export const envVars = validateEnvVars();
