import { EnvSchema } from './env.schema';

const processEnv = {
  // PC
  PC_DOMAIN: process.env.PC_DOMAIN,
  PC_CLIENT_ID: process.env.PC_CLIENT_ID,
  PC_CLIENT_SECRET: process.env.PC_CLIENT_SECRET,
  PC_ID_TOKEN_SIGNED_RESPONSE_ALG: process.env.PC_ID_TOKEN_SIGNED_RESPONSE_ALG,
  PC_USERINFO_SIGNED_RESPONSE_ALG: process.env.PC_USERINFO_SIGNED_RESPONSE_ALG,
  PC_REDIRECT_URI: process.env.PC_REDIRECT_URI,
  // Auth
  AUTH_TOKEN_NAME: process.env.AUTH_TOKEN_NAME,
  REFRESH_TOKEN_NAME: process.env.REFRESH_TOKEN_NAME,
  IS_LOGGED_TOKEN_NAME: process.env.IS_LOGGED_TOKEN_NAME,
  AUTH_TOKEN_EXPIRATION: process.env.AUTH_TOKEN_EXPIRATION,
  REFRESH_TOKEN_EXPIRATION: process.env.REFRESH_TOKEN_EXPIRATION,
  AUTH_TOKEN_SECRET_KEY: process.env.AUTH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
  // Frontend
  FRONTEND_URI: process.env.FRONTEND_URI,
  FRONTEND_REDIRECT_URI: process.env.FRONTEND_REDIRECT_URI,
  FRONTEND_REDIRECT_LOGIN_URI: process.env.FRONTEND_REDIRECT_LOGIN_URI,
  // DematSocial
  DEMAT_SOCIAL_API_URL: process.env.DEMAT_SOCIAL_API_URL,
  DEMAT_SOCIAL_API_TOKEN: process.env.DEMAT_SOCIAL_API_TOKEN,
  DEMAT_SOCIAL_API_DIRECTORY: process.env.DEMAT_SOCIAL_API_DIRECTORY,
  // Internal
  LOG_FORMAT: process.env.LOG_FORMAT,
  LOG_LEVEL: process.env.LOG_LEVEL,
  TRUSTED_IP_HEADERS: process.env.TRUSTED_IP_HEADERS,
  LOG_EXTRA_CONTEXT: process.env.LOG_EXTRA_CONTEXT,
  SUPER_ADMIN_LIST_EMAIL: process.env.SUPER_ADMIN_LIST_EMAIL,
  // Sentry
  SENTRY_ENABLED: process.env.SENTRY_ENABLED,
  SENTRY_DSN_BACKEND: process.env.SENTRY_DSN_BACKEND,
  SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
  // Minio
  S3_BUCKET_ACCESS_KEY: process.env.S3_BUCKET_ACCESS_KEY,
  S3_BUCKET_SECRET_KEY: process.env.S3_BUCKET_SECRET_KEY,
  S3_BUCKET_ENDPOINT: process.env.S3_BUCKET_ENDPOINT,
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
  S3_BUCKET_REGION: process.env.S3_BUCKET_REGION,
  S3_BUCKET_ROOT_DIR: process.env.S3_BUCKET_ROOT_DIR,
  S3_BUCKET_PORT: process.env.S3_BUCKET_PORT,
  // Sarbacane
  SARBACANE_API_URL: process.env.SARBACANE_API_URL,
  SARBACANE_API_KEY: process.env.SARBACANE_API_KEY,
  // Cron
  CRON_DEMAT_SOCIAL: process.env.CRON_DEMAT_SOCIAL,
  // Redis
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
};

const validateEnvVars = () => EnvSchema.parse(processEnv);

export const envVars = validateEnvVars();
