---
SDPSN-devops-charts:
  namespace: org-sdpsn-ws-sirena-production

  deployment:
    replicas: 2

  ingress:
    host: sirena-sante.social.gouv.fr
    tls:
      hosts:
        - sirena-sante.social.gouv.fr
        - sirena-sante.social.prod.atlas.fabrique.social.gouv.fr
