export const EXPORT_REQUETES_HEADERS = [
  'Numéro de requête',
  'Le déclarant est la personne concernée',
  'Lien avec la personne concernée',
  'Le déclarant est tuteur/curateur de la personne concernée',
  'Code Postal déclarant',
  'Le déclarant consent à ce que son identité soit communiquée',
  'Déclarant est un professionnel qui déclare un EIG ',
  'Civilité Personne concernée',
  'Tranche age personne concernée',
  'Si tranche non renseignée : Année de naissance personne concernée',
  'Code Postal personne concernée',
  'La personne concernée consent à ce que son identité soit communiquée',
  'La personne concernée a été informée de la démarche par le déclarant',
  'Mesure de protection de la personne concernée',
  'La personne concernée est en situation de handicap',
  'Autre personne concernée par la requête',
  'Numéro de situation',
  'Type de lieu de survenue',
  'Précision type de lieu de survenue',
  'Numéro FINESS du lieu de survenue',
  'Catégorie établissement du FINESS du lieu de survenue',
  "Nom de l'établissement / Nom du lieu de survenue / Société de transport concernée",
  'Code postal lieu de survenue',
  'Type de mis en cause',
  'Précision type de mis en cause',
  'FINESS mis en cause',
  'Catégorie établissement du FINESS mis en cause',
  'Nom du service',
  'RPPS mis en cause',
  'Nom mis en cause',
  'Code postal mis en cause',
  'Catégorie professionnelle du RPPS mis en cause ',
  'Motifs renseignés par le déclarant (dans demat.social ou plateforme téléphonique)',
  "Motifs qualifiés par l'agent",
  'Conséquences sur la personne concernée',
  'Date début des faits',
  'Date fin des faits',
  'Domaine fonctionnel',
  'Le mis en cause a été contacté',
  'Date de prise de contact',
  'Le déclarant a réçu une réponse',
  'Une plainte a été déposée auprès des autorités judiciaires',
  'Date de dépot de plate',
  'Lieu de dépot de plainte',
  "Des démarches ont été engagées auprès d'autres organismes",
  'Entités administratives affectées à la situation ',
  'Directions affectées à la situation',
  'Services affectés à la situation',
  'Entités (+statut entité) affectées à la requête',
  'Priorité de la requête pour mon entité adminsitrative',
  'Date création requête dans SIRENA',
  'Date réception',
  'Mode de réception',
  'Date demande par le déclarant',
  'Provenance',
  "Date envoi de l'accusé de réception pour mon entité administrative",
  "Type d'envoi de l'accusé de réception",
  'Dernière date de clôture de la requête pour mon entité administrative',
  'Raison(s) clôture de la requête pour mon entité administrative',
] as const;
