export const EXPORT_REQUETES_COLUMNS = [
  {
    key: 'statutRequeteEntiteAdministrative',
    header: 'Statut de la requête pour mon entité administrative',
  },
  { key: 'numeroRequete', header: 'Numéro de requête' },
  { key: 'declarantEstPersonneConcernee', header: 'Le déclarant est la personne concernée' },
  { key: 'lienPersonneConcernee', header: 'Lien avec la personne concernée' },
  {
    key: 'declarantEstTuteurCurateur',
    header: 'Le déclarant est tuteur/curateur de la personne concernée',
  },
  { key: 'codePostalDeclarant', header: 'Code Postal déclarant' },
  { key: 'departementDeclarant', header: 'Département déclarant' },
  {
    key: 'declarantConsentIdentiteCommuniquee',
    header: 'Le déclarant consent à ce que son identité soit communiquée',
  },
  { key: 'declarantProfessionnelEig', header: 'Déclarant est un professionnel qui déclare un EIG' },
  { key: 'civilitePersonneConcernee', header: 'Civilité Personne concernée' },
  { key: 'trancheAgePersonneConcernee', header: 'Tranche age personne concernée' },
  {
    key: 'anneeNaissancePersonneConcernee',
    header: 'Si tranche non renseignée : Année de naissance personne concernée',
  },
  { key: 'codePostalPersonneConcernee', header: 'Code Postal personne concernée' },
  { key: 'departementPersonneConcernee', header: 'Département personne concernée' },
  {
    key: 'personneConcerneeConsentIdentiteCommuniquee',
    header: 'La personne concernée consent à ce que son identité soit communiquée',
  },
  {
    key: 'personneConcerneeInformeeDemarche',
    header: 'La personne concernée a été informée de la démarche par le déclarant',
  },
  { key: 'mesureProtectionPersonneConcernee', header: 'Mesure de protection de la personne concernée' },
  { key: 'personneConcerneeHandicap', header: 'La personne concernée est en situation de handicap' },
  { key: 'autrePersonneConcernee', header: 'Autre personne concernée par la requête' },
  { key: 'numeroSituation', header: 'Numéro de situation' },
  { key: 'typeLieuSurvenue', header: 'Type de lieu de survenue' },
  { key: 'precisionTypeLieuSurvenue', header: 'Précision type de lieu de survenue' },
  { key: 'finessLieuSurvenue', header: 'Numéro FINESS du lieu de survenue' },
  { key: 'categorieFinessLieuSurvenue', header: 'Catégorie établissement du FINESS du lieu de survenue' },
  {
    key: 'nomLieuSurvenue',
    header: "Nom de l'établissement / Nom du lieu de survenue / Société de transport concernée",
  },
  { key: 'codePostalLieuSurvenue', header: 'Code postal lieu de survenue' },
  { key: 'departementLieuSurvenue', header: 'Département lieu de survenue' },
  { key: 'typeMisEnCause', header: 'Type de mis en cause' },
  { key: 'precisionTypeMisEnCause', header: 'Précision type de mis en cause' },
  { key: 'finessMisEnCause', header: 'FINESS mis en cause' },
  { key: 'categorieFinessMisEnCause', header: 'Catégorie établissement du FINESS mis en cause' },
  { key: 'nomService', header: 'Nom du service' },
  { key: 'departementMisEnCause', header: 'Département mis en cause' },
  {
    key: 'motifsDeclaratifs',
    header: 'Motifs renseignés par le déclarant (dans demat.social ou plateforme téléphonique)',
  },
  { key: 'motifsQualifies', header: "Motifs qualifiés par l'agent" },
  { key: 'consequencesPersonneConcernee', header: 'Conséquences sur la personne concernée' },
  { key: 'dateDebutFaits', header: 'Date début des faits' },
  { key: 'dateFinFaits', header: 'Date fin des faits' },
  { key: 'domaineFonctionnel', header: 'Domaine fonctionnel' },
  { key: 'misEnCauseContacte', header: 'Le mis en cause a été contacté' },
  { key: 'datePriseContact', header: 'Date de prise de contact' },
  { key: 'declarantRecuReponse', header: 'Le déclarant a réçu une réponse' },
  { key: 'plainteDeposee', header: 'Une plainte a été déposée auprès des autorités judiciaires' },
  { key: 'dateDepotPlainte', header: 'Date de dépôt de plainte' },
  { key: 'lieuDepotPlainte', header: 'Lieu de dépot de plainte' },
  { key: 'demarchesAutresOrganismes', header: "Des démarches ont été engagées auprès d'autres organismes" },
  { key: 'entitesAdministrativesSituation', header: 'Entités administratives affectées à la situation' },
  { key: 'directionsSituation', header: 'Directions affectées à la situation' },
  { key: 'servicesSituation', header: 'Services affectés à la situation' },
  { key: 'entitesStatutsRequete', header: 'Entités (+statut entité) affectées à la requête' },
  { key: 'prioriteRequeteEntiteAdministrative', header: 'Priorité de la requête pour mon entité adminsitrative' },
  { key: 'dateCreationRequeteSirena', header: 'Date création requête dans SIRENA' },
  { key: 'dateReception', header: 'Date réception' },
  { key: 'modeReception', header: 'Mode de réception' },
  { key: 'dateDemandeDeclarant', header: 'Date demande par le déclarant' },
  { key: 'provenance', header: 'Provenance' },
  {
    key: 'dateEnvoiAccuseReceptionEntiteAdministrative',
    header: "Date envoi de l'accusé de réception pour mon entité administrative",
  },
  { key: 'typeEnvoiAccuseReception', header: "Type d'envoi de l'accusé de réception" },
  {
    key: 'derniereDateClotureEntiteAdministrative',
    header: 'Dernière date de clôture de la requête pour mon entité administrative',
  },
  {
    key: 'raisonsClotureEntiteAdministrative',
    header: 'Raison(s) clôture de la requête pour mon entité administrative',
  },
] as const;

export type ExportRequetesColumnKey = (typeof EXPORT_REQUETES_COLUMNS)[number]['key'];

export const EXPORT_REQUETES_HEADERS = EXPORT_REQUETES_COLUMNS.map((column) => column.header);
