{{- if .Values.enabled }}
{{- if .Values.externalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anonymize-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName | default "secret-store" }}
    kind: SecretStore
  target:
    name: anonymize-secret
  data:
    - secretKey: PG_URL_FROM
      remoteRef:
        key: {{ .Values.externalSecret.key }}
        property: PG_URL_FROM
    - secretKey: PG_URL_TO
      remoteRef:
        key: {{ .Values.externalSecret.key }}
        property: PG_URL_TO
{{- end }}
{{- end }}
