{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anonymize-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: local-secret-store
  target:
    name: anonymize-secret
  data:
    - secretKey: PG_URL_FROM
      remoteRef:
        key: {{ .Values.sirena_db_secret_path }}
        property: url
    - secretKey: PG_URL_TO
      remoteRef:
        key: {{ .Values.anonymize_db_secret_path }}
        property: url
{{- end }}
