-- Roll back MotifEnum labels to the pre-V6 referential values.
INSERT INTO "MotifEnum" ("id", "label")
VALUES
  ('ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES', 'Non respect des règles (hygiène, conformité des locaux, consentement éclairé, tarifs pratiqués, formations…)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/ACCESSIBILITE_LOCAUX', 'Accessibilité des locaux (aux personnes à mobilité réduite, parking…)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/CONFIGURATION_LOCAUX', 'Configuration des locaux (équipement sanitaire, superficie chambre, équipements divers)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/ENTRETIEN', 'Entretien (fenêtre endommagé, digicode non fonctionnel, …)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/EQUIPEMENTS_USAGE_PERSONNEL', 'Les équipements à usage personnel (télévision…)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/GESTION_RESSOURCES_BIENS', 'La gestion des ressources ou des biens de la personne (dépôt, vols, perte…)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/HYGIENE', 'Hygiène (entretien, ménage…)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_LOCAUX', 'Sécurité des locaux (locaux mal sécurisé)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_PERSONNES', 'Sécurité des personnes (chute...)'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SERVICE_RESTAURATION', 'Service de restauration (horaires des repas, quantité servie, qualité des repas…)'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_ACCOMPAGNEMENT_FIN_VIE', 'Informations sur l''accompagnement à la fin de vie (Loi Léonetti, demande évolutions législation)'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_DESIGNATION_PERSONNE_CONFIANCE', 'Informations sur la désignation d''une personne de confiance'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_EVENEMENT', 'Informations du patient et résident suite à un événement (indésirable)'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_PATHOLOGIE', 'Informations du patient sur sa pathologie, son opération, les risques encourus'),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_CONSULTATION_PROFESSIONNEL_LIBERAL', 'Refus de consultation par un professionnel de santé libéral '),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_INTERVENTION_DOMICILE', 'Refus d''intervention au domicile (exemple : SOS médecins, IDEL ...)'),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_FAMILLE_PROFESSIONNELS', 'Relations entre la famille/l''entourage et les professionnels'),
  ('PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE', 'Exercice illegal / usurpation de titre (médecine ou autre profession)'),
  ('PROBLEMES_ENVIRONNEMENTAUX/GESTION_DECHETS_DASRI', 'Problématiques ou gestion des déchets d''activités de soins à risques infectieux (DASRI)'),
  ('PROBLEMES_ENVIRONNEMENTAUX/SITUATION_EXCEPTIONNELLE', 'Situation exceptionnelle (exemple : canicule, innondations..)'),
  ('PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNELS_ENCADRANT_INSTITUTS', 'Manque de personnels encadrant dans les instituts de formation (profession para-médical et sociale)'),
  ('PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_QUALIFICATION_PERSONNEL', 'Manque de qualification du personnel (diplôme...)'),
  ('PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT', 'Conditions de prise en charge du patient au début et à la fin (par exemple, délai d''attente, lieu de dépôt...)'),
  ('PROBLEMES_TRANSPORT_SANITAIRE/NON_RESPECT_DISPOSITIONS_REGLEMENTAIRES', 'Non-respect des dispositions réglementaires en vigueur (absence de tenue professionnelle, véhicule nonconforme et hygiène, non-respect de l''obligation de présence d''un ambulancier dans la cellule sanitaire...)'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/DEFAUT_SURVEILLANCE', 'Défaut de surveillance (fugue / disparition inquiétante)'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEMATIQUE_FONCTIONNEMENT_ESSMS', 'Problématique de fonctionnement de l''ESSMS (règlement intérieur, …)'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEME_ACCOMPAGNEMENT_SUIVI_INDIVIDUEL', 'Problème d''accompagnement et/ou suivi individuel : projet de vie, suivi social, éducatif, administratif…'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/QUALITE_ANIMATIONS_LIEU_INTERVENTIONS', 'Qualité des animations au lieu d''interventions'),
  ('QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX', 'Absence ou insuffisance de soins paramédicaux (repas, hygiène…)'),
  ('QUALITE_SOINS/AFFECTIONS_IATROGENES', 'Affections iatrogénes : infections liées aux soins, infections nosocomiales, événements liés à un produit de santé'),
  ('QUALITE_SOINS/CONDITIONS_PRELEVEMENTS_BIOLOGIQUES', 'Les conditions de prélèvements biologiques'),
  ('QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE', 'Défaillance ou incident lié aux soins ou à la surveillance (complications, incapacité, décès)'),
  ('QUALITE_SOINS/DELAIS_PRISE_EN_CHARGE', 'Délais de prise en charge'),
  ('QUALITE_SOINS/ETAT_MATERIEL', 'Etat du matériel (en rapport avec les soins)'),
  ('QUALITE_SOINS/SOINS_PALLIATIFS', 'Soins palliatifs (absence ou défaut de plan de soin)')
ON CONFLICT ("id") DO UPDATE SET "label" = EXCLUDED."label";
