-- Sync MotifEnum labels with the code referential (Liste des motifs V6).
-- Label-only update of existing rows: no id added/removed, no FaitMotif data touched.
INSERT INTO "MotifEnum" ("id", "label")
VALUES
  ('ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES', 'Non respect des règles'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/ACCESSIBILITE_LOCAUX', 'Accessibilité des locaux'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/CONFIGURATION_LOCAUX', 'Configuration des locaux'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/ENTRETIEN', 'Entretien'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/EQUIPEMENTS_USAGE_PERSONNEL', 'Équipements à usage personnel'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/GESTION_RESSOURCES_BIENS', 'Gestion des ressources ou des biens de la personne'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/HYGIENE', 'Hygiène'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_LOCAUX', 'Sécurité des locaux'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_PERSONNES', 'Sécurité des personnes'),
  ('HOTELLERIE_LOCAUX_RESTAURATION/SERVICE_RESTAURATION', 'Service de restauration'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_ACCOMPAGNEMENT_FIN_VIE', 'Défaut d''information sur l''accompagnement à la fin de vie'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_DESIGNATION_PERSONNE_CONFIANCE', 'Défaut d''information sur la désignation d''une personne de confiance'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_EVENEMENT', 'Défaut d''information suite à un événement indésirable'),
  ('INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_PATHOLOGIE', 'Défaut d''information sur une pathologie, une opération ou les risques encourus'),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_CONSULTATION_PROFESSIONNEL_LIBERAL', 'Refus de consultation par un professionnel de santé libéral'),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_INTERVENTION_DOMICILE', 'Refus d''intervention au domicile'),
  ('MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_FAMILLE_PROFESSIONNELS', 'Relations entre l''entourage et les professionnels'),
  ('PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE', 'Exercice illégal ou usurpation de titre'),
  ('PROBLEMES_ENVIRONNEMENTAUX/GESTION_DECHETS_DASRI', 'Gestion des déchets d''activités de soins à risques infectieux (DASRI)'),
  ('PROBLEMES_ENVIRONNEMENTAUX/SITUATION_EXCEPTIONNELLE', 'Situation exceptionnelle'),
  ('PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNELS_ENCADRANT_INSTITUTS', 'Manque de personnels encadrant dans les instituts de formation'),
  ('PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_QUALIFICATION_PERSONNEL', 'Manque de qualification du personnel'),
  ('PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT', 'Conditions de prise en charge du patient'),
  ('PROBLEMES_TRANSPORT_SANITAIRE/NON_RESPECT_DISPOSITIONS_REGLEMENTAIRES', 'Non-respect des dispositions réglementaires en vigueur'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/DEFAUT_SURVEILLANCE', 'Défaut de surveillance'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEMATIQUE_FONCTIONNEMENT_ESSMS', 'Problématique de fonctionnement de l''ESSMS'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEME_ACCOMPAGNEMENT_SUIVI_INDIVIDUEL', 'Problème d''accompagnement ou suivi individuel'),
  ('QUALITE_ACCOMPAGNEMENT_SERVICE/QUALITE_ANIMATIONS_LIEU_INTERVENTIONS', 'Qualité des animations au lieu d''intervention'),
  ('QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX', 'Absence ou insuffisance de soins paramédicaux'),
  ('QUALITE_SOINS/AFFECTIONS_IATROGENES', 'Affections iatrogénes'),
  ('QUALITE_SOINS/CONDITIONS_PRELEVEMENTS_BIOLOGIQUES', 'Conditions de prélèvements biologiques'),
  ('QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE', 'Défaillance ou incident lié aux soins ou à la surveillance'),
  ('QUALITE_SOINS/DELAIS_PRISE_EN_CHARGE', 'Délai de prise en charge'),
  ('QUALITE_SOINS/ETAT_MATERIEL', 'État du matériel'),
  ('QUALITE_SOINS/SOINS_PALLIATIFS', 'Soins palliatifs')
ON CONFLICT ("id") DO UPDATE SET "label" = EXCLUDED."label";
