-- RemoveForeignKey
ALTER TABLE "Requete" DROP CONSTRAINT IF EXISTS "Requete_provenanceId_fkey";

-- DropColumn
ALTER TABLE "Requete" DROP COLUMN IF EXISTS "provenancePrecision";
ALTER TABLE "Requete" DROP COLUMN IF EXISTS "provenanceId";

-- Delete enum rows
DELETE FROM "RequeteProvenanceEnum" WHERE "id" IN (
  'AUTO_SAISINE_PARTICULIER', 'AUTO_SAISINE_PRO', 'PRESIDENCE_REPUBLIQUE', 'ELUS',
  'PREFECTURE', 'ARS', 'CONSEIL_DEPARTEMENTAL', 'DDETS_DREETS', 'PREMIER_MINISTRE',
  'MINISTERES', 'PRESIDENCE_AN_SENAT', 'IGAS', 'PARQUET', 'DEFENSEUR_DROITS',
  'CONSEILS_ORDRE', 'ASSOCIATIONS_USAGERS', 'ASSURANCE_MALADIE', 'DEMANDE_SDIS', 'AUTRE'
);

-- DropTable
DROP TABLE IF EXISTS "RequeteProvenanceEnum";
