DELETE FROM "public"."MisEnCauseTypePrecisionEnum" WHERE ("id", "misEnCauseTypeId") IN (
  ('PARENT','MEMBRE_FAMILLE'),
  ('CONJOINT','MEMBRE_FAMILLE'),
  ('ENFANT','MEMBRE_FAMILLE'),
  ('AUTRE','MEMBRE_FAMILLE'),
  ('ENTOURAGE_SOCIAL','PROCHE'),
  ('AUTRE','PROCHE'),
  ('AUTRE','AUTRE_PERSONNE_NON_PRO'),
  ('MEDECIN_GENERALISTE','PROFESSIONNEL_SANTE'),
  ('MEDECIN_SPECIALISTE','PROFESSIONNEL_SANTE'),
  ('MEDEC','PROFESSIONNEL_SANTE'),
  ('IDEC','PROFESSIONNEL_SANTE'),
  ('IBODE','PROFESSIONNEL_SANTE'),
  ('INFIRMIER','PROFESSIONNEL_SANTE'),
  ('SAGE_FEMME','PROFESSIONNEL_SANTE'),
  ('CADRE_SANTE','PROFESSIONNEL_SANTE'),
  ('PHARMACIEN','PROFESSIONNEL_SANTE'),
  ('AIDE_SOIGNANT','PROFESSIONNEL_SANTE'),
  ('ASH','PROFESSIONNEL_SANTE'),
  ('BIOLOGISTE','PROFESSIONNEL_SANTE'),
  ('AMBULANCIER','PROFESSIONNEL_SANTE'),
  ('BRANCARDIER','PROFESSIONNEL_SANTE'),
  ('AUTRE','PROFESSIONNEL_SANTE'),
  ('ASSISTANT_SOCIAL','PROFESSIONNEL_SOCIAL'),
  ('INTERVENANT_SOCIAL','PROFESSIONNEL_SOCIAL'),
  ('EDUCATEUR_SPECIALISE','PROFESSIONNEL_SOCIAL'),
  ('ANIMATEUR','PROFESSIONNEL_SOCIAL'),
  ('CESF','PROFESSIONNEL_SOCIAL'),
  ('MANDATAIRE','PROFESSIONNEL_SOCIAL'),
  ('AUTRE','PROFESSIONNEL_SOCIAL'),
  ('RESPONSABLE_ETABLISSEMENT','AUTRE_PROFESSIONNEL'),
  ('AGENT_ACCUEIL_ADMIN','AUTRE_PROFESSIONNEL'),
  ('CHEF_SERVICE','AUTRE_PROFESSIONNEL'),
  ('TATOUEUR','AUTRE_PROFESSIONNEL'),
  ('PSYCHANALYSTE','AUTRE_PROFESSIONNEL'),
  ('PSYCHOLOGUE','AUTRE_PROFESSIONNEL'),
  ('PSYCHOTHERAPEUTE','AUTRE_PROFESSIONNEL'),
  ('DIETETICIEN','AUTRE_PROFESSIONNEL'),
  ('OSTEOPATHE','AUTRE_PROFESSIONNEL'),
  ('CHIROPRACTEUR','AUTRE_PROFESSIONNEL'),
  ('ORTHOPHONISTE','AUTRE_PROFESSIONNEL'),
  ('AUDIOPROTHESISTE','AUTRE_PROFESSIONNEL'),
  ('EPITHESISTE','AUTRE_PROFESSIONNEL'),
  ('MANIPULATEUR_RADIO','AUTRE_PROFESSIONNEL'),
  ('OCULAIRE_OPTIQUE','AUTRE_PROFESSIONNEL'),
  ('ORTHOPEDISTE','AUTRE_PROFESSIONNEL'),
  ('ORTHESISTE','AUTRE_PROFESSIONNEL'),
  ('PSYCHOMOTRICIEN','AUTRE_PROFESSIONNEL'),
  ('TECHNICIEN_LABO','AUTRE_PROFESSIONNEL'),
  ('ACUPUNCTEUR','AUTRE_PROFESSIONNEL'),
  ('EQUIPE_MOBILE','AUTRE_PROFESSIONNEL'),
  ('SAPEUR_POMPIER','AUTRE_PROFESSIONNEL'),
  ('MEDECINE_NON_CONVENTIONNELLE','AUTRE_PROFESSIONNEL'),
  ('ESTHETICIEN','AUTRE_PROFESSIONNEL'),
  ('AUTRE','AUTRE_PROFESSIONNEL'),
  ('PROF_SANTE','PROFESSIONNEL_SANTE'),
  ('TRAVAILLEUR_SOCIAL','PROFESSIONNEL_SANTE'),
  ('PROF_SOIN','PROFESSIONNEL_SANTE'),
  ('RESPONSABLE','PROFESSIONNEL_SANTE'),
  ('MJPM','PROFESSIONNEL_SANTE'),
  ('PROF_LIBERAL','PROFESSIONNEL_SANTE'),
  ('HAD','PROFESSIONNEL_SANTE'),
  ('SSAD','PROFESSIONNEL_SANTE'),
  ('SAMSAH','PROFESSIONNEL_SANTE'),
  ('SAEMO','PROFESSIONNEL_SANTE'),
  ('SESSAD','PROFESSIONNEL_SANTE'),
  ('SAED','PROFESSIONNEL_SANTE'),
  ('SPST','PROFESSIONNEL_SANTE'),
  ('AIDE_MENAGERE','PROFESSIONNEL_SANTE'),
  ('REPAS','PROFESSIONNEL_SANTE'),
  ('TRAITEMENT','PROFESSIONNEL_SANTE'),
  ('SAADF','PROFESSIONNEL_SANTE'),
  ('SSIAD','PROFESSIONNEL_SANTE'),
  ('SAAD','PROFESSIONNEL_SANTE')
);

DELETE FROM "public"."AgeEnum" WHERE "id" IN (
  '-18',
  '18-29',
  '30-59',
  '60-79',
  '>= 80',
  'Inconnu'
);

DELETE FROM "public"."AutoriteTypeEnum" WHERE "id" IN (
  'GENDARMERIE',
  'COMMISSARIAT',
  'TRIBUNAL'
);

DELETE FROM "public"."CiviliteEnum" WHERE "id" IN (
  'M',
  'MME',
  'MX',
  'NSP'
);

DELETE FROM "public"."ConsequenceEnum" WHERE "id" IN (
  'SANTE',
  'DROITS',
  'BESOINS',
  'SOCIAL',
  'AUCUNE'
);

DELETE FROM "public"."DemarchesEngageesEnum" WHERE "id" IN (
  'CONTACT_RESPONSABLES',
  'CONTACT_ORGANISME',
  'PLAINTE',
  'AUTRE'
);

DELETE FROM "public"."EntiteTypeEnum" WHERE "id" IN (
  'ARS',
  'DD',
  'CD'
);

DELETE FROM "public"."LienVictimeEnum" WHERE "id" IN (
  'MEMBRE_FAMILLE',
  'PROCHE',
  'PROFESSIONNEL',
  'AUTRE'
);

DELETE FROM "public"."LieuTypeEnum" WHERE "id" IN (
  'DOMICILE',
  'ETABLISSEMENT_SANTE',
  'ETABLISSEMENT_PERSONNES_AGEES',
  'ETABLISSEMENT_HANDICAP',
  'ETABLISSEMENT_SOCIAL',
  'AUTRES_ETABLISSEMENTS',
  'TRAJET'
);

DELETE FROM "public"."MaltraitanceTypeEnum" WHERE "id" IN (
  'NEGLIGENCES',
  'VIOLENCES',
  'MATERIELLE_FINANCIERE',
  'SEXUELLE',
  'NON'
);

DELETE FROM "public"."MisEnCauseTypeEnum" WHERE "id" IN (
  'MEMBRE_FAMILLE',
  'PROCHE',
  'AUTRE_PERSONNE_NON_PRO',
  'PROFESSIONNEL_SANTE',
  'PROFESSIONNEL_SOCIAL',
  'NPJM',
  'AUTRE_PROFESSIONNEL',
  'AUTRE'
);

DELETE FROM "public"."MotifEnum" WHERE "id" IN (
  'ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/AUTRES',
  'ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/DEFAUT_DECLARATION_ACTIVITE',
  'ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES',
  'MEDICAMENTS/PROBLEMATIQUE_CIRCUIT_MEDICAMENT',
  'MEDICAMENTS/STOCKAGE_MEDICAMENTS',
  'MEDICAMENTS/VENTE_MEDICAMENTS_INTERNET',
  'FACTURATIONS_HONORAIRES/AUTRES',
  'FACTURATIONS_HONORAIRES/PROBLEME_HONORAIRES',
  'FACTURATIONS_HONORAIRES/PROBLEME_FACTURATION',
  'FACTURATIONS_HONORAIRES/HONORAIRES_PROFESSIONS_LIBERALES',
  'HOTELLERIE_LOCAUX_RESTAURATION/ACCESSIBILITE_LOCAUX',
  'HOTELLERIE_LOCAUX_RESTAURATION/ACCUEIL',
  'HOTELLERIE_LOCAUX_RESTAURATION/ADMISSION',
  'HOTELLERIE_LOCAUX_RESTAURATION/AUTRES',
  'HOTELLERIE_LOCAUX_RESTAURATION/CONFIGURATION_LOCAUX',
  'HOTELLERIE_LOCAUX_RESTAURATION/ENTRETIEN',
  'HOTELLERIE_LOCAUX_RESTAURATION/HYGIENE',
  'HOTELLERIE_LOCAUX_RESTAURATION/GESTION_RESSOURCES_BIENS',
  'HOTELLERIE_LOCAUX_RESTAURATION/EQUIPEMENTS_USAGE_PERSONNEL',
  'HOTELLERIE_LOCAUX_RESTAURATION/ABSENCE_LIEU_ACCUEIL_FAMILLE',
  'HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_LOCAUX',
  'HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_PERSONNES',
  'HOTELLERIE_LOCAUX_RESTAURATION/SERVICE_RESTAURATION',
  'INFORMATIONS_DROITS_USAGERS/INFO_ACCOMPAGNEMENT_FIN_VIE',
  'INFORMATIONS_DROITS_USAGERS/AUTRES',
  'INFORMATIONS_DROITS_USAGERS/DOSSIER_MEDICAL_NON_COMMUNIQUE',
  'INFORMATIONS_DROITS_USAGERS/INFO_DESIGNATION_PERSONNE_CONFIANCE',
  'INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_EVENEMENT',
  'INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_PATHOLOGIE',
  'INFORMATIONS_DROITS_USAGERS/MODALITES_ANNONCE_DECES',
  'INFORMATIONS_DROITS_USAGERS/RECUEIL_CONSENTEMENT',
  'INFORMATIONS_DROITS_USAGERS/NON_RESPECT_SECRET_MEDICAL',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/DISCRIMINATIONS',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/EXPOSITION_ENVIRONNEMENT_VIOLENT',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/NEGLIGENCES_ACTIVES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/NEGLIGENCES_PASSIVES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/PRIVATION_SOIN_BESOINS_FONDAMENTAUX',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/PRIVATION_VIOLATION_DROITS_LIBERTES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_MATERIELLES_FINANCIERES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_MEDICALES_MEDICAMENTEUSES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_PHYSIQUES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_PSYCHIQUES_MORALES',
  'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_SEXUELLES',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/AUTRES',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/DEFAUT_ENCADREMENT_STAGE',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_AIDE_PROFESSIONNEL',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_FAMILLE_PROFESSIONNELS',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_USAGER_PROFESSIONNELS',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_CONSULTATION_PROFESSIONNEL_LIBERAL',
  'MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_INTERVENTION_DOMICILE',
  'PRATIQUE_NON_CONVENTIONNELLE/DERIVES_SECTAIRES',
  'PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/CONFLIT_DIRECTION_ETABLISSEMENT',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/CONFLIT_SOCIAL',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNELS_ENCADRANT_INSTITUTS',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNEL_SOIGNANT',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/ABSENCE_MEDEC',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_QUALIFICATION_PERSONNEL',
  'PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNEL_NON_SOIGNANT',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEME_ACCOMPAGNEMENT_SUIVI_INDIVIDUEL',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/NON_RESPECT_PROGRAMMES_FORMATION',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/ABSENCE_ANIMATION',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/AUTRES',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/QUALITE_ANIMATIONS_LIEU_INTERVENTIONS',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEMATIQUE_FONCTIONNEMENT_ESSMS',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/VIOLENCES_ENTRE_USAGERS',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/VIOLENCES_USAGER_ENTOURAGE',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/VIOLENCES_USAGER_PROFESSIONNEL',
  'QUALITE_ACCOMPAGNEMENT_SERVICE/DEFAUT_SURVEILLANCE',
  'QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_MEDICAUX',
  'QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX',
  'QUALITE_SOINS/ABSENCE_INSUFFISANCE_REEDUCATION',
  'QUALITE_SOINS/AFFECTIONS_IATROGENES',
  'QUALITE_SOINS/AIDE_MEDICALE_URGENTE_SAMU',
  'QUALITE_SOINS/AUTRES',
  'QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE',
  'QUALITE_SOINS/DELAIS_PRISE_EN_CHARGE',
  'QUALITE_SOINS/DIAGNOSTIC_PERTINENCE_EXAMENS',
  'QUALITE_SOINS/ETAT_MATERIEL',
  'QUALITE_SOINS/CONDITIONS_PRELEVEMENTS_BIOLOGIQUES',
  'QUALITE_SOINS/PRISE_EN_CHARGE_DOULEUR',
  'QUALITE_SOINS/RESULTATS_EXAMENS',
  'QUALITE_SOINS/SOINS_PALLIATIFS',
  'QUALITE_SOINS/SOINS_POST_MORTEM',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/AUTRES',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/GARDE_PERMANENCE_SOINS_AMBULATOIRES',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/MEDECIN_TRAITANT',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/SPECIALISTE',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/RECHERCHE_SMR',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/ETABLISSEMENT_MEDICO_SOCIAL_PA',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/ETABLISSEMENT_MEDICO_SOCIAL_PH',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/TRANSFERT_MANQUE_LIT',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/DELAIS_ATTENTE_PLACE_ETABLISSEMENT',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/RECHERCHE_SERVICE_ACCOMPAGNEMENT_DOMICILE_PA',
  'DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/RECHERCHE_SERVICE_ACCOMPAGNEMENT_DOMICILE_PH',
  'PROBLEMES_ENVIRONNEMENTAUX/GESTION_DECHETS_DASRI',
  'PROBLEMES_ENVIRONNEMENTAUX/SITUATION_EXCEPTIONNELLE',
  'PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_CONDUITE_VEHICULE',
  'PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT',
  'PROBLEMES_TRANSPORT_SANITAIRE/DEFAUT_OFFRE',
  'PROBLEMES_TRANSPORT_SANITAIRE/DEFAUT_GARDE',
  'PROBLEMES_TRANSPORT_SANITAIRE/NON_RESPECT_DISPOSITIONS_REGLEMENTAIRES',
  'PROBLEMES_TRANSPORT_SANITAIRE/TRANSFERT_ENTRE_ETABLISSEMENTS'
);

DELETE FROM "public"."MotifDeclaratifEnum" WHERE "id" IN (
  'PROBLEME_COMPORTEMENTAL',
  'PROBLEME_FACTURATION',
  'PROBLEME_LOCAUX',
  'NON_RESPECT_DROITS',
  'PROBLEME_ORGANISATION',
  'PROBLEME_QUALITE_SOINS',
  'DIFFICULTES_ACCES_SOINS',
  'AUTRE'
);

DELETE FROM "public"."ReceptionTypeEnum" WHERE "id" IN (
  'EMAIL',
  'COURRIER',
  'FORMULAIRE',
  'PLATEFORME',
  'TELEPHONE',
  'AUTRE'
);

DELETE FROM "public"."RequeteClotureReasonEnum" WHERE "id" IN (
  'MESURES_CORRECTIVES',
  'ABSENCE_DE_RETOUR',
  'HORS_COMPETENCE',
  'MISSION_D_INSPECTION_ET_CONTROLE',
  'SANS_SUITE',
  'AUTRE'
);

DELETE FROM "public"."RequeteEtapeStatutEnum" WHERE "id" IN (
  'EN_COURS',
  'A_FAIRE',
  'FAIT',
  'CLOTUREE'
);

DELETE FROM "public"."RequetePrioriteEnum" WHERE "id" IN (
  'HAUTE',
  'MOYENNE',
  'BASSE'
);

DELETE FROM "public"."RoleEnum" WHERE "id" IN (
  'PENDING',
  'READER',
  'WRITER',
  'NATIONAL_STEERING',
  'ENTITY_ADMIN',
  'SUPER_ADMIN'
);

DELETE FROM "public"."StatutEnum" WHERE "id" IN (
  'ACTIF',
  'INACTIF',
  'NON_RENSEIGNE'
);

DELETE FROM "public"."TransportTypeEnum" WHERE "id" IN (
  'POMPIER',
  'ASSU',
  'VSAV',
  'AMBULANCE',
  'VSL',
  'TAXI',
  'AUTRE'
);
