name: "Deploy to GitOps"
description: "Generate Kubernetes manifests and deploy to GitOps repository"

inputs:
  environment:
    description: "Environment name (test, integration, etc.)"
    required: true
  version:
    description: "Version identifier for versioning (tag name or short SHA)"
    required: true
  gitops-repo:
    description: "GitOps repository name"
    required: false
    default: "fabrique-atlas/org-sdpsn-ws-sirena"
  gitops-repo-key:
    description: "SSH key for GitOps repository access"
    required: true

runs:
  using: "composite"
  steps:
    - name: Audit dependencies
      shell: bash
      run: |
        cd deploy
        npm audit --audit-level=moderate
    - name: Install dependencies
      shell: bash
      run: |
        cd deploy
        npm ci

    - name: Check format and lint
      shell: bash
      run: |
        cd deploy
        npm run lint

    - name: Render manifests
      shell: bash
      run: |
        cd deploy
        export IMAGE_TAG=${{ inputs.version }}
        export ENVIRONNEMENT=${{ inputs.environment }}
        npm run build

    - name: Checkout GitOps repository
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.gitops-repo }}
        path: gitops-repo
        ssh-key: ${{ inputs.gitops-repo-key }}

    - name: Deploy to GitOps
      shell: bash
      run: |
        rm -r gitops-repo/deployment-targets/${{ inputs.environment }}
        cp -r deploy/dist gitops-repo/deployment-targets/${{ inputs.environment }}

        git config --global user.name "github-actions[bot]"
        # mail standard bot github Actions
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        cd gitops-repo
        git add .

        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit, skipping commit and push"
        else
          git commit -m '[${{ inputs.environment }}] new version ${{ inputs.version }}'
          git push
        fi
