{{ if .Values.externalSecret.mariadbSirec.enable }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-sirec-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: local-secret-store
  data:
    - secretKey: MARIADB_SIREC_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.mariadbSirec.vaultPath }}
        property: {{ .Values.externalSecret.mariadbSirec.passwordKey }}
  target:
    name: mariadb-sirec-secret
    template:
      data:
        MARIADB_SIREC_HOST: {{ .Values.externalSecret.mariadbSirec.host | quote }}
        MARIADB_SIREC_PORT: {{ .Values.externalSecret.mariadbSirec.port | quote }}
        MARIADB_SIREC_DB: {{ .Values.externalSecret.mariadbSirec.db | quote }}
        MARIADB_SIREC_USER: {{ .Values.externalSecret.mariadbSirec.user | quote }}
        MARIADB_SIREC_PASSWORD: {{`"{{ .MARIADB_SIREC_PASSWORD }}"`}}
{{- end }}
