{{ if .Values.externalSecret.migrationBucket.enable }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.migrationBucket.targetSecretName }}
spec:
  dataFrom:
    - extract:
        key: buckets/{{ .Values.externalSecret.migrationBucket.bucketName }}
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: local-secret-store
  target:
    name: {{ .Values.externalSecret.migrationBucket.targetSecretName }}
    template:
      data:
        S3_MIGRATION_BUCKET_ACCESS_KEY: {{`"{{ .accessKey }}"`}}
        S3_MIGRATION_BUCKET_NAME: {{`"{{ .name }}"`}}
        S3_MIGRATION_BUCKET_SECRET_KEY: {{`"{{ .secretKey }}"`}}
{{- end }}
