import type { EntiteSirenaLabels } from './affectation.transco.js';

export const AFFECTATION_ENTITES_PAYS_DE_LA_LOIRE: Record<number, [EntiteSirenaLabels, ...EntiteSirenaLabels[]]> = {
  1025: [{ label: 'DG Communication', parentLabel: 'ARS Pays de la Loire' }],
  1019: [{ label: 'DOS RHS', parentLabel: 'ARS Pays de la Loire' }],
  1077: [{ label: 'DT44 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  1079: [{ label: 'DT49 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  1081: [{ label: 'DT53 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  1083: [{ label: 'DT72 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  1085: [{ label: 'DT85 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  1017: [{ label: 'DG DIC', parentLabel: 'ARS Pays de la Loire' }],
  1013: [{ label: 'DG Démocratie sanitaire', parentLabel: 'ARS Pays de la Loire' }],
  1015: [{ label: 'DG Interventions', parentLabel: 'ARS Pays de la Loire' }],
  1011: [{ label: 'DG Juridique', parentLabel: 'ARS Pays de la Loire' }],
  1009: [{ label: 'DOS AES', parentLabel: 'ARS Pays de la Loire' }],
  1007: [{ label: 'DOS ASP', parentLabel: 'ARS Pays de la Loire' }],
  1023: [{ label: 'DOS Investissement', parentLabel: 'ARS Pays de la Loire' }],
  1021: [{ label: 'DOS AES', parentLabel: 'ARS Pays de la Loire' }],
  1003: [{ label: 'DASM PPA', parentLabel: 'ARS Pays de la Loire' }],
  1005: [{ label: 'DASM PPH', parentLabel: 'ARS Pays de la Loire' }],
  1001: [{ label: 'DSPE VSSSE', parentLabel: 'ARS Pays de la Loire' }],
  963: [{ label: 'DT44 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  965: [{ label: 'DT44 SPE', parentLabel: 'ARS Pays de la Loire' }],
  967: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
  969: [{ label: 'DT44 Transports sanitaires', parentLabel: 'ARS Pays de la Loire' }],
  971: [{ label: 'DT49 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  973: [{ label: 'DT49 SPE', parentLabel: 'ARS Pays de la Loire' }],
  975: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
  977: [{ label: 'DT49 Transports sanitaires', parentLabel: 'ARS Pays de la Loire' }],
  979: [{ label: 'DT53 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  981: [{ label: 'DT53 SPE', parentLabel: 'ARS Pays de la Loire' }],
  983: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
  985: [{ label: 'DT72 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  987: [{ label: 'DT72 SPE', parentLabel: 'ARS Pays de la Loire' }],
  989: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
  991: [{ label: 'DT72 Transports sanitaires', parentLabel: 'ARS Pays de la Loire' }],
  993: [{ label: 'DT85 Parcours', parentLabel: 'ARS Pays de la Loire' }],
  995: [{ label: 'DT85 SPE', parentLabel: 'ARS Pays de la Loire' }],
  997: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
  999: [{ label: 'DT85 Transports sanitaires', parentLabel: 'ARS Pays de la Loire' }],
  2193: [{ label: 'DASM SPSC - Santé Mentale', parentLabel: 'ARS Pays de la Loire' }],
};
