{{ if .Values.externalSecret.database.enable }}
---
# Fait pour surcharger le template pour matcher la spécificité de Sirena. Il faut que l'appli change les varaibles lues pour la connexino à la DB
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.database.databaseType }}/{{ .Values.externalSecret.database.databaseName }}
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: local-secret-store
  target:
    name: {{ .Values.externalSecret.database.targetSecretName }}
    template:
      data:
        PG_SIRENA_DB: {{`"{{ .dbname }}"`}}
        PG_HOST: {{`"{{ .host }}"`}}
        PG_SIRENA_PASSWORD: {{`"{{ .password }}"`}}
        PG_PORT: {{`"{{ .port }}"`}}
        PG_URL: {{`"{{ .url }}"`}}
        PG_SIRENA_USER: {{`"{{ .username }}"`}}
{{- end }}
