-- CreateEnum
CREATE TYPE "Role" AS ENUM ('PENDING', 'READER', 'WRITER', 'PILOTING', 'LOCAL_ADMIN', 'GLOBAL_ADMIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'PENDING';
