---
SDPSN-devops-charts:
  namespace: org-sdpsn-ws-sirena-production

  certificateIssuer:
    enable: true

  appVariables:
    HOST: https://sirena-sante.social.gouv.fr
    PC_DOMAIN: https://auth.agentconnect.gouv.fr/api/v2
    PC_REDIRECT_URI: https://sirena-sante.social.gouv.fr/api/auth/callback
    FRONTEND_REDIRECT_URI: https://sirena-sante.social.gouv.fr/home
    FRONTEND_REDIRECT_LOGIN_URI: https://sirena-sante.social.gouv.fr/login
    FRONTEND_URI: https://sirena-sante.social.gouv.fr
    REDIS_TLS: "true"
    SENTRY_ENVIRONMENT: production

  deployment:
    replicas: 2

  ingress:
    host: sirena-sante.social.gouv.fr
    appAnnotations:
      external-dns.alpha.kubernetes.io/hostname: sirena-sante.social.prod.atlas.fabrique.social.gouv.fr
    tls:
      hosts:
        - sirena-sante.social.gouv.fr
        - sirena-sante.social.prod.atlas.fabrique.social.gouv.fr
