export const SIREC_DICO: Record<number, string> = {
  2: 'A renseigner',
  4: 'Autres',
  10: 'Courrier',
  12: 'Courriel',
  14: 'Téléphone',
  16: 'ARS uniquement',
  18: 'ARS et autres destinataires en copie',
  20: 'Autres destinataires et ARS en copie',
  22: 'Personne moral',
  24: 'Personne physique',
  26: 'Premier Ministre',
  28: 'Elus',
  30: 'Ministrère de la justice',
  34: "L'usager (victime)",
  36: "Différent de l'usager (victime)",
  38: 'Masculin',
  40: 'Féminin',
  42: 'Paris',
  44: 'Troyes',
  46: 'Famille',
  50: 'ARS',
  52: 'Partagée',
  54: 'Hors ARS',
  55: 'Pré-identification',
  56: 'Identification',
  57: 'Affectation',
  58: 'Traitement',
  59: 'Réponse',
  60: 'Éléments de langage',
  61: "Lettre à la signature du DG d'ARS",
  62: 'Copie de réponse au requérant',
  63: 'Aucune réponse attendue',
  64: 'FINESS',
  65: 'RPPS',
  66: 'Sans mis en cause',
  67: 'Autres',
  68: 'Addictologie',
  69: 'Algologie',
  70: 'Ambulatoire',
  71: 'Adultes',
  72: 'Enfants',
  73: 'Handicapés',
  74: '1',
  75: 'Oui',
  76: 'Non',
  77: 'Ne sait pas',
  78: 'Ambulatoire - Transport sanitaire',
  79: 'Autres',
  80: "Défaut d'offre de soins - Cas critique",
  81: "Défaut d'offre de soins - Général",
  82: 'Détenus',
  83: 'Hospitalisations sous contrainte',
  84: 'Médico-Social - Handicapés adultes',
  85: 'Médico-Social - Handicapés enfants',
  86: 'Médico-Social - Personnes âgées',
  87: 'Pharmacies-Laboratoires',
  88: 'Sanitaire',
  89: 'Info par média',
  90: 'Sur pièce(s)',
  91: 'Sur place',
  94: 'EI',
  95: 'EIG',
  96: 'EIGLS',
  97: 'Aucun',
  98: 'Mis en cause',
  99: 'ARS',
  100: 'Clôture',
  101: 'Nombre de réclamations traitées',
  102: 'Nombre de réclamations par domaine fonctionnel',
  103: 'Institution 1',
  104: 'Institution 2',
  105: 'Institution 3',
  106: 'Autre',
  107: 'Autre',
  108: 'Curatelle',
  109: 'Sauvegarde de justice',
  110: 'Tutelle',
  111: 'Non',
  112: 'Oui',
  113: 'A renseigner',
  114: 'Ambulatoire - Général',
  115: 'Clôturé "sans suite"',
  116: 'Clôturé "hors compétence"',
  117: 'Un',
  118: 'Deux',
  119: 'Trois',
  120: 'Acuponcteur',
  121: 'Chiropracteur',
  122: 'Etablissement fictif',
  123: 'Exercice illégal',
  124: "Maison d'arrêt",
  125: 'Ostéopathe',
  126: 'Professionnel de santé hors RPPS',
  127: 'Psychothérapeute',
  128: 'Structure hors FINESS',
  129: 'Tatoueur',
  130: 'Transporteur Sanitaire',
  131: 'Autre',
  132: 'Liste des modes de réception (écran identification)',
  133: 'Liste des destinataire(s) de la demande du requérant (écran identification)',
  134: "Liste des réponses attendues par l'institution de provenance (écran identification)",
  136: "Service d'accueil des urgences",
  138: 'Service de réanimation',
  140: 'SOS médecin',
  142: 'Autre',
  144: 'PU-PH, MCU-PH, PH',
  146: 'PHC, Attaché',
  148: 'CCA/Assistant',
  150: 'Interne',
  152: 'Non renseigné',
  154: 'Homme',
  156: 'Femme',
  158: 'Sonde urinaire',
  160: 'Cathéter central',
  162: 'Valve cardiaque',
  164: 'Pace maker',
  166: 'Autre',
  168: 'Infection du système nerveux central',
  170: 'Infection ORL',
  172: 'Infection broncho-pulmonaire',
  174: 'Infection cardiaque',
  176: 'Infection urinaire',
  178: 'Infection intra-abdominale',
  180: 'Infection génitale/IST',
  182: 'Infection cutanéo-muqueuse',
  184: 'Infection ostéo-articulaire',
  186: 'Infection généralisée/bactériémie',
  188: 'Infection sur cathéter',
  190: 'Infection autre (oculaire, stomatologique…)',
  192: 'Fièvre chez un sujet neutropénique',
  194: 'Infection liée au VIH/SIDA',
  196: 'Paludisme',
  198: 'Infection liée aux voyages',
  200: 'Infection et grossesse',
  202: 'Infection du site opératoire',
  204: 'Antibioprophylaxie',
  206: 'Choc septique',
  208: 'Sepsis grave',
  210: 'Détresse respiratoire',
  212: 'trouble de la conscience',
  214: 'Défaillance hémodynamique',
  216: 'ECBU',
  218: 'Hémoculture',
  220: 'PL',
  222: 'Autre',
  224: "Entérobactérie sécrétrice d'une bétalactamase à spectre élargi (BLSE)",
  226: 'Staphylococcus aureus résistant à la méticilline (SARM)',
  228: 'Entérocoque résistant à la vancomycine (ERV)',
  230: 'Entérobactérie productrice de carbapénèmase (EPC)',
  232: 'Autre',
  234: 'Exposition au sang et aux liquides biologiques',
  236: 'Exposition sexuelle',
  238: 'Positif',
  240: 'Inconnu',
  242: 'Traitement ARV en cours',
  244: 'Charge virale détectable',
  246: 'Charge virale indétectable',
  248: 'Groupe à prévalence élevée *',
  250: 'Groupe à prévalence faible',
  252: 'Important (piqure profond, aiguille creuse et intravasculaire)',
  254: 'Intermédiaire (coupure avec bistouri, piqure avec aiguille IM, SC, pleine, exposition cutanéo-muqueuse avec temps de contact > 15 minutes)',
  256: 'Minime (piqures avec seringues abandonnées, crachats, morsures ou griffures)',
  258: 'Positif',
  260: 'Inconnu',
  262: 'Traitement ARV en cours',
  264: 'Charge virale détectable',
  266: 'Charge virale indétectable',
  268: 'Groupe à prévalence élevée *',
  270: 'Groupe à prévalence faible',
  272: 'Rapport anal réceptif',
  274: 'Rapport anal insertif',
  276: 'Rapport vaginal réceptif',
  278: 'Rapport vaginal insertif',
  280: 'Fellation',
  282: 'Positif',
  284: 'Négatif',
  286: 'Vacciné',
  288: 'Inconnu',
  290: 'Positif',
  292: 'Négatif',
  294: 'Inconnu',
  296: "Initiation d'un traitement anti infectieux",
  298: 'Poursuivre le traitement anti infectieux en cours',
  300: 'Arrêt du traitement anti infectieux en cours',
  302: 'Modification du traitement anti infectieux en cours',
  304: "Pas d'indication à un traitement anti rétro viral / anti infectieux",
  306: "Indication d'un traitement anti rétro viral / anti infectieux",
  308: 'Relais à effectuer',
  310: 'Adaptation de la posologie',
  312: "Adaptation des modalités d'administration",
  314: 'Adaptation de la durée',
  316: "Adaptation de la voie d'administration",
  318: 'Avis diagnostic',
  320: 'Avis thérapeutique',
  322: 'Avis sur un prélèvement microbiologique',
  324: 'Avis pour un AES',
  326: 'Autre (texte libre pour préciser)',
  328: 'Information',
  330: 'Alerte',
  332: 'Adultes',
  334: 'Handicapés',
  336: 'Autres',
  338: 'Portail des signalements',
  340: 'Autre',
  344: "Communication d'un délai d'attente au requérant",
  346: "Relance de l'ARS par le requérant",
  348: "Saisine du procureur par l'ARS",
  350: "Information au requérant de la saisine du procureur par l'ARS",
  352: "Demande de consentement au requérant (pour la transmission d'éléments de son dossier)",
  354: 'Autre',
  356: "Demande au mis en cause de pièces justificatives ou d'éléments complémentaires",
  358: 'Relance du mis en cause',
  360: 'Réponse du mis en cause',
  362: 'Instruction par un médecin ou autre(s) expert(s) ARS',
  364: 'Transmission de la réclamation au mis en cause pour instruction',
  366: 'Demande au mis en cause de la copie de la réponse faite au requérant',
  368: 'Relance du mis en cause pour communication de la copie de la réponse',
  370: 'Copie de la réponse faite au requérant par le mis en cause',
  372: "Recommandations à l'établissement",
  374: 'Inspection',
  376: 'Visite ou entretien avec le mis en cause',
  377: 'Nombre de réclamations par type(s) de traitement',
  379: "Nombre de réclamations clôturées hors compétences de l'ARS",
  381: 'Nombre de réclamations ayant entrainé la saisine du procureur par le requérant',
  383: "Demande au mis en cause de pièces justificatives ou d'éléments complémentaires",
  385: 'Relance du mis en cause',
  387: 'Réponse du mis en cause',
  389: 'Instruction par un médecin ou autre(s) expert(s) ARS',
  391: 'Transmission de la réclamation au mis en cause pour instruction',
  393: 'Demande au mis en cause de la copie de la réponse faite au requérant',
  395: 'Relance du mis en cause pour communication de la copie de la réponse',
  397: 'Copie de la réponse faite au requérant par le mis en cause',
  399: "Recommandations à l'établissement",
  401: 'Inspection',
  403: 'Visite ou entretien avec le mis en cause',
  404: 'Assurance Maladie',
  406: 'Chefferie de la division des Cabinets',
  408: "Conseils de l'Ordre",
  410: 'Conseil départemental ou régional',
  412: 'Directe',
  414: 'DRJSCS – DDCS',
  416: 'Défenseur des Droits',
  418: 'Inspection Générale des Affaires Sociales',
  420: 'Ministère des Solidarités et de la Santé',
  422: 'Observatoire des prisons (OIP)',
  424: 'Préfecture de Département ou de Région',
  426: 'Présidence de la République',
  428: "Présidence de l'Assemblée Nationale ou du Sénat",
  430: "Associations / Représentants / Collectifs d'usagers",
  432: "Secrétariat d'état chargé de l'Égalité entre les femmes et les hommes",
  434: "Secrétariat d'état chargé des personnes handicapées",
  436: 'Autre',
  438: 'Anesthésie',
  440: 'Assistance médicale à la procréation et diagnostic prénatal',
  442: 'Cardiologie',
  444: 'Centre 15',
  446: 'Centres de ressources et de compétences de la muco',
  448: 'Chirurgie',
  450: 'Consultations externes',
  452: 'Dermatologie',
  454: 'Dialyse',
  456: 'Gastro-Entérologie et Hépatologie',
  458: 'Gériatrie',
  460: 'Greffe',
  462: 'Gynécologie-obstétrique, néonatologie, réanimation néonatale',
  464: 'Hématologie',
  466: 'Hospitalisation à domicile (HAD)',
  468: 'Imagerie médicale',
  470: 'Laboratoire de biologie',
  472: 'Médecine',
  474: 'Néphrologie',
  476: 'Neurochirurgie',
  478: 'Neurologie',
  480: 'Traitement du cancer',
  482: 'Ophtalmologie',
  484: 'Orthopédie',
  486: 'Oto-Rhino-Laryngologie (ORL)',
  488: 'Pédiatrie',
  490: 'Permanence des soins ambulatoires (PDSA)',
  492: 'Pharmacie / PUI',
  494: 'Pneumologie',
  496: "Prélèvement d'organe",
  498: 'Psychiatrie',
  500: 'Radiologie',
  502: 'Réanimation',
  504: 'Rééducation fonctionnelle',
  506: 'Rhumatologie',
  508: 'Service intervenant en milieu carcéral (UCSA/SMPR)',
  510: 'Soins de suite et de réadaptation',
  512: 'Soins de longue durée',
  514: 'Soins palliatifs',
  516: 'Stomatologie',
  518: 'Surveillance et de soins continus',
  520: 'Traitement des grands brûlés',
  522: 'Traumatologie',
  524: 'Unité de Soins Intensifs Cardiologiques (USIC)',
  526: 'Urgences / SAMU et SMUR',
  528: 'Urologie',
  530: 'Autre',
  531: 'Prioritaire',
  532: 'Nombre de signalements saisis',
  534: 'Nombre de réclamations par professionnel de santé du RPPS (TOP 20)',
  536: 'Nombre de réclamations par établissement FINESS (TOP 20)',
  538: 'Nombre de réclamations par service pour les établissements sanitaires (TOP 20)',
  540: 'Nombre de réclamations par motif IGAS',
  541: 'Validation de la pré-identification',
  543: "Validation de l'identification",
  545: "Validation de l'affectation",
  547: 'Validation du traitement',
  549: 'Clôture de la réclamation',
  551: 'Clôture sans suite de la réclamation',
  553: "Clôture hors compétences de l'ARS",
  555: 'Déclôture de la réclamation',
  557: 'Affectation au service',
  559: 'Partage au service',
  561: 'Suppression',
  562: "Affectation d'un traitement",
  564: "Partage d'un traitement",
  566: 'Réponse',
  568: 'Ain',
  570: 'Aisne',
  572: '1',
  574: '1',
  592: 'Santé environnement',
  594: 'Allier',
  596: 'Alpes-de-Haute-Provence',
  598: 'Hautes-Alpes',
  600: 'Alpes-Maritimes',
  602: 'Ardèche',
  604: 'Ardennes',
  606: 'Ariège',
  608: 'Aube',
  610: 'Aude',
  612: 'Aveyron',
  614: 'Bouches-du-Rhône',
  616: 'Calvados',
  618: 'Cantal',
  620: 'Charente',
  622: 'Charente-Maritime',
  624: 'Cher',
  626: 'Corrèze',
  628: 'Corse-du-Sud',
  630: 'Haute-Corse',
  632: "Côte-d'Or",
  634: "Côtes-d'Armor",
  636: 'Creuse',
  638: 'Dordogne',
  640: 'Doubs',
  642: 'Drôme',
  644: 'Eure',
  646: 'Eure-et-Loir',
  648: 'Finistère',
  650: 'Gard',
  652: 'Haute-Garonne',
  654: 'Gers',
  656: 'Gironde',
  658: 'Hérault',
  660: 'Ille-et-Vilaine',
  662: 'Indre',
  664: 'Indre-et-Loire',
  666: 'Isère',
  668: 'Jura',
  670: 'Landes',
  672: 'Loir-et-Cher',
  674: 'Loire',
  676: 'Haute-Loire',
  678: 'Loire-Atlantique',
  680: 'Loiret',
  682: 'Lot',
  684: 'Lot-et-Garonne',
  686: 'Lozère',
  688: 'Maine-et-Loire',
  690: 'Manche',
  692: 'Marne',
  694: 'Haute-Marne',
  696: 'Mayenne',
  698: 'Meurthe-et-Moselle',
  700: 'Meuse',
  702: 'Morbihan',
  704: 'Moselle',
  706: 'Nièvre',
  708: 'Nord',
  710: 'Oise',
  712: 'Orne',
  714: 'Pas-de-Calais',
  716: 'Puy-de-Dôme',
  718: 'Pyrénées-Atlantiques',
  720: 'Hautes-Pyrénées',
  722: 'Pyrénées-Orientales',
  724: 'Bas-Rhin',
  726: 'Haut-Rhin',
  728: 'Rhône',
  730: 'Haute-Saône',
  732: 'Saône-et-Loire',
  734: 'Sarthe',
  736: 'Savoie',
  738: 'Haute-Savoie',
  740: 'Paris',
  742: 'Seine-Maritime',
  744: 'Seine-et-Marne',
  746: 'Yvelines',
  748: 'Deux-Sèvres',
  750: 'Somme',
  752: 'Tarn',
  754: 'Tarn-et-Garonne',
  756: 'Var',
  758: 'Vaucluse',
  760: 'Vendée',
  762: 'Vienne',
  764: 'Haute-Vienne',
  766: 'Vosges',
  768: 'Yonne',
  770: 'Territoire de Belfort',
  772: 'Essonne',
  774: 'Hauts-de-Seine',
  776: 'Seine-Saint-Denis',
  778: 'Val-de-Marne',
  780: "Val-d'Oise",
  782: 'Guadeloupe',
  784: 'Martinique',
  786: 'Guyane',
  788: 'La Réunion',
  790: 'Saint-Pierre-et-Miquelon',
  792: 'Mayotte',
  793: 'Saint-Martin et Saint-Barthélemy',
  794: 'Autre',
  796: 'Clôturé "absence de retour/accord du requérant"',
  798: 'Clôturé "réponse ARS apportée au requérant"',
  800: 'Clôturé "réponse du mis en cause apportée au requérant"',
  802: 'Clôturé "mission d\'inspection et contrôle"',
  803: 'Formulaire dématérialisé',
  804: 'DREETS',
  806: 'DDEETS',
  807: 'Problème lié à des actes esthétiques',
  809: 'Problème lié à la facturation ou aux honoraires',
  811: 'Problème lié aux locaux ou la restauration',
  813: "Non-respect des droits des usagers dont défaut d'information",
  815: "Maltraitance (action ou défaut d'action individuelle, collective ou institutionnelle)",
  817: 'Problème relationnel ou de communication avec le professionnel',
  819: "Problème d'organisation ou de fonctionnement de l'établissement ou du service",
  821: 'Problème de qualité des soins médicaux ou paramédicaux',
  823: "Difficultés d'accès aux soins (établissement ou professionnel)",
  825: 'Signal Conso',
};
