import { DOMAINES_FONCTIONNELS } from '@sirena/common/constants';
import { SirecTranscoError } from './sirecTransco.error.js';

const DOMAINE_FONCTIONNEL_TRANSCO: Record<number, string> = {
  114: DOMAINES_FONCTIONNELS.AMBULATOIRE_GENERAL,
  78: DOMAINES_FONCTIONNELS.AMBULATOIRE_TRANSPORT_SANITAIRE,
  79: DOMAINES_FONCTIONNELS.AUTRES,
  80: DOMAINES_FONCTIONNELS.DEFAUT_OFFRE_SOINS_CAS_CRITIQUE,
  81: DOMAINES_FONCTIONNELS.DEFAUT_OFFRE_SOINS_GENERAL,
  82: DOMAINES_FONCTIONNELS.AUTRES,
  83: DOMAINES_FONCTIONNELS.HOSPITALISATIONS_CONTRAINTE,
  84: DOMAINES_FONCTIONNELS.MEDICO_SOCIAL_HANDICAPES_ADULTES,
  85: DOMAINES_FONCTIONNELS.MEDICO_SOCIAL_HANDICAPES_ENFANTS,
  86: DOMAINES_FONCTIONNELS.MEDICO_SOCIAL_PA,
  87: DOMAINES_FONCTIONNELS.PHARMACIES_LABORATOIRES,
  88: DOMAINES_FONCTIONNELS.SANITAIRE,
  592: DOMAINES_FONCTIONNELS.SANTE_ENVIRONNEMENT,
};

const DOMAINE_NULL_IDS = new Set([113]);

export function transcodeDomaineFonctionnel(idSirec: number | null): string | null {
  if (idSirec === null || DOMAINE_NULL_IDS.has(idSirec)) return null;
  const domaineId = DOMAINE_FONCTIONNEL_TRANSCO[idSirec];
  if (domaineId === undefined) throw new SirecTranscoError(idSirec, 'domaine');
  return domaineId;
}
