import { motifLabelsById } from '@sirena/common/constants';
import { createDefaultLogger } from '../../../helpers/pino.js';
import { SirecDataError } from './sirecTransco.error.js';

export const MOTIF_IGAS_A_RENSEIGNER = 155;
export const MOTIF_IGAS_HORS_COMPETENCE = 184;

interface MotifIgasTranscoEntry {
  motifIds: string[];
  // id_igas du motif Igas parent. Quand un mis en cause porte à la fois ce motif et son parent,
  // le parent doit être ignoré lors de la migration (voir resolveMotifsIgas).
  parentMotifId?: number;
}

// TODO : enlever les motifs en commentaire quand la correspondance aura été validée.
const MOTIFS_IGAS_TRANSCO: Record<number, MotifIgasTranscoEntry> = {
  153: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/AUTRES'], parentMotifId: 19 },
  146: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES'], parentMotifId: 19 },
  147: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/DEFAUT_DECLARATION_ACTIVITE'], parentMotifId: 19 },
  148: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES'], parentMotifId: 19 },
  149: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/DEFAUT_DECLARATION_ACTIVITE'], parentMotifId: 19 },
  150: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/NON_RESPECT_REGLES'], parentMotifId: 19 },
  151: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/DEFAUT_DECLARATION_ACTIVITE'], parentMotifId: 19 },
  152: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/AUTRES'], parentMotifId: 19 },
  122: { motifIds: ['FACTURATIONS_HONORAIRES/AUTRES'], parentMotifId: 17 },
  216: { motifIds: ['FACTURATIONS_HONORAIRES/HONORAIRES_PROFESSIONS_LIBERALES'], parentMotifId: 17 },
  214: { motifIds: ['FACTURATIONS_HONORAIRES/PROBLEME_FACTURATION'], parentMotifId: 17 },
  20: {
    motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/ADMISSION', 'HOTELLERIE_LOCAUX_RESTAURATION/ACCUEIL'],
    parentMotifId: 10,
  },
  30: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/ABSENCE_LIEU_ACCUEIL_FAMILLE'], parentMotifId: 10 },
  26: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/ACCESSIBILITE_LOCAUX'], parentMotifId: 10 },
  21: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/AUTRES'], parentMotifId: 10 },
  33: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/AUTRES'], parentMotifId: 10 },
  25: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/CONFIGURATION_LOCAUX'], parentMotifId: 10 },
  29: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/EQUIPEMENTS_USAGE_PERSONNEL'], parentMotifId: 10 },
  31: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/GESTION_RESSOURCES_BIENS'], parentMotifId: 10 },
  27: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/HYGIENE'], parentMotifId: 10 },
  186: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_LOCAUX'], parentMotifId: 10 },
  32: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_PERSONNES'], parentMotifId: 10 },
  28: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/SERVICE_RESTAURATION'], parentMotifId: 10 },
  24: {
    motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/ENTRETIEN', 'HOTELLERIE_LOCAUX_RESTAURATION/SECURITE_LOCAUX'],
    parentMotifId: 10,
  },
  23: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT'], parentMotifId: 10 },
  109: { motifIds: ['INFORMATIONS_DROITS_USAGERS/AUTRES'], parentMotifId: 16 },
  104: { motifIds: ['INFORMATIONS_DROITS_USAGERS/DOSSIER_MEDICAL_NON_COMMUNIQUE'], parentMotifId: 16 },
  107: { motifIds: ['INFORMATIONS_DROITS_USAGERS/INFO_ACCOMPAGNEMENT_FIN_VIE'], parentMotifId: 16 },
  98: { motifIds: ['INFORMATIONS_DROITS_USAGERS/INFO_DESIGNATION_PERSONNE_CONFIANCE'], parentMotifId: 16 },
  96: { motifIds: ['INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_EVENEMENT'], parentMotifId: 16 },
  95: { motifIds: ['INFORMATIONS_DROITS_USAGERS/INFO_PATIENT_PATHOLOGIE'], parentMotifId: 16 },
  106: { motifIds: ['INFORMATIONS_DROITS_USAGERS/MODALITES_ANNONCE_DECES'], parentMotifId: 16 },
  103: { motifIds: ['INFORMATIONS_DROITS_USAGERS/NON_RESPECT_SECRET_MEDICAL'], parentMotifId: 16 },
  97: { motifIds: ['INFORMATIONS_DROITS_USAGERS/RECUEIL_CONSENTEMENT'], parentMotifId: 16 },
  99: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/DISCRIMINATIONS'], parentMotifId: 16 },
  100: {
    motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_CONSULTATION_PROFESSIONNEL_LIBERAL'],
    parentMotifId: 16,
  },
  101: {
    motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_CONSULTATION_PROFESSIONNEL_LIBERAL'],
    parentMotifId: 16,
  },
  102: { motifIds: ['INFORMATIONS_DROITS_USAGERS/AUTRES'], parentMotifId: 16 },
  105: { motifIds: ['INFORMATIONS_DROITS_USAGERS/AUTRES'], parentMotifId: 16 },
  108: { motifIds: ['INFORMATIONS_DROITS_USAGERS/AUTRES'], parentMotifId: 16 },
  162: {
    motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/EXPOSITION_ENVIRONNEMENT_VIOLENT'],
    parentMotifId: 158,
  },
  88: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_MATERIELLES_FINANCIERES'], parentMotifId: 158 },
  84: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_PHYSIQUES'], parentMotifId: 158 },
  85: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_PSYCHIQUES_MORALES'], parentMotifId: 158 },
  83: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_SEXUELLES'], parentMotifId: 158 },
  160: {
    motifIds: [
      'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/NEGLIGENCES_ACTIVES',
      'MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/NEGLIGENCES_PASSIVES',
    ],
    parentMotifId: 158,
  },
  164: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/VIOLENCES_PHYSIQUES_ENTRE_USAGERS'], parentMotifId: 158 },
  //166: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/AUTRES'], parentMotifId: 158 },
  86: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/NEGLIGENCES_ACTIVES'], parentMotifId: 15 },
  87: {
    motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/PRIVATION_VIOLATION_DROITS_LIBERTES'],
    parentMotifId: 15,
  },
  89: {
    motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/VIOLENCES_MEDICALES_MEDICAMENTEUSES'],
    parentMotifId: 15,
  },
  82: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/AUTRES'], parentMotifId: 15 },
  94: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/AUTRES'], parentMotifId: 15 },
  92: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/DEFAUT_ENCADREMENT_STAGE'], parentMotifId: 15 },
  91: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_AIDE_PROFESSIONNEL'], parentMotifId: 15 },
  81: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_FAMILLE_PROFESSIONNELS'], parentMotifId: 15 },
  80: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/RELATIONS_USAGER_PROFESSIONNELS'], parentMotifId: 15 },
  90: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/VIOLENCES_SEXUELLES_ENTRE_USAGERS'], parentMotifId: 15 },
  93: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/AUTRES'], parentMotifId: 15 },
  180: { motifIds: ['PRATIQUE_NON_CONVENTIONNELLE/DERIVES_SECTAIRES'], parentMotifId: 176 },
  178: { motifIds: ['PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE'], parentMotifId: 176 },
  182: { motifIds: ['PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE'], parentMotifId: 176 },
  47: { motifIds: ['MEDICAMENTS/VENTE_MEDICAMENTS_INTERNET'], parentMotifId: 11 },
  39: { motifIds: ['PRATIQUE_NON_CONVENTIONNELLE/EXERCICE_ILLEGAL_USURPATION_TITRE'], parentMotifId: 11 },
  208: {
    motifIds: ['PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNEL_NON_SOIGNANT'],
    parentMotifId: 11,
  },
  206: { motifIds: ['PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNEL_SOIGNANT'], parentMotifId: 11 },
  42: {
    motifIds: ['PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_PERSONNELS_ENCADRANT_INSTITUTS'],
    parentMotifId: 11,
  },
  38: {
    motifIds: ['PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/MANQUE_QUALIFICATION_PERSONNEL'],
    parentMotifId: 11,
  },
  41: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/ABSENCE_ANIMATION'], parentMotifId: 11 },
  48: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/AUTRES'], parentMotifId: 11 },
  43: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/NON_RESPECT_PROGRAMMES_FORMATION'], parentMotifId: 11 },
  40: {
    motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/PROBLEME_ACCOMPAGNEMENT_SUIVI_INDIVIDUEL'],
    parentMotifId: 11,
  },
  196: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/AUTRES'], parentMotifId: 11 },
  51: { motifIds: ['QUALITE_SOINS/DELAIS_PRISE_EN_CHARGE'], parentMotifId: 12 },
  53: { motifIds: ['MEDICAMENTS/PROBLEMATIQUE_CIRCUIT_MEDICAMENT'], parentMotifId: 12 },
  62: { motifIds: ['MEDICAMENTS/PROBLEMATIQUE_CIRCUIT_MEDICAMENT'], parentMotifId: 12 },
  58: { motifIds: ['QUALITE_SOINS/AFFECTIONS_IATROGENES'], parentMotifId: 12 },
  63: { motifIds: ['QUALITE_SOINS/AIDE_MEDICALE_URGENTE_SAMU'], parentMotifId: 12 },
  64: { motifIds: ['QUALITE_SOINS/AUTRES'], parentMotifId: 12 },
  60: { motifIds: ['QUALITE_SOINS/CONDITIONS_PRELEVEMENTS_BIOLOGIQUES'], parentMotifId: 12 },
  210: { motifIds: ['QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE'], parentMotifId: 12 },
  212: { motifIds: ['QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE'], parentMotifId: 12 },
  49: { motifIds: ['QUALITE_SOINS/DELAIS_PRISE_EN_CHARGE'], parentMotifId: 12 },
  50: { motifIds: ['QUALITE_SOINS/DIAGNOSTIC_PERTINENCE_EXAMENS'], parentMotifId: 12 },
  52: { motifIds: ['QUALITE_SOINS/ETAT_MATERIEL'], parentMotifId: 12 },
  59: { motifIds: ['QUALITE_SOINS/PRISE_EN_CHARGE_DOULEUR'], parentMotifId: 12 },
  61: { motifIds: ['QUALITE_SOINS/RESULTATS_EXAMENS'], parentMotifId: 12 },
  188: { motifIds: ['QUALITE_SOINS/SOINS_PALLIATIFS'], parentMotifId: 12 },
  68: { motifIds: ['MEDICAMENTS/PROBLEMATIQUE_CIRCUIT_MEDICAMENT'], parentMotifId: 13 },
  65: { motifIds: ['QUALITE_SOINS/ABSENCE_INSUFFISANCE_REEDUCATION'], parentMotifId: 13 },
  66: { motifIds: ['QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX'], parentMotifId: 13 },
  67: { motifIds: ['QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX'], parentMotifId: 13 },
  190: { motifIds: ['QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX'], parentMotifId: 13 },
  72: { motifIds: ['QUALITE_SOINS/AUTRES'], parentMotifId: 13 },
  69: { motifIds: ['QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE'], parentMotifId: 13 },
  70: { motifIds: ['QUALITE_SOINS/DEFAILLANCE_INCIDENT_SOINS_SURVEILLANCE'], parentMotifId: 13 },
  71: { motifIds: ['QUALITE_SOINS/SOINS_POST_MORTEM'], parentMotifId: 13 },
  79: { motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/AUTRES'], parentMotifId: 14 },
  78: {
    motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/GARDE_PERMANENCE_SOINS_AMBULATOIRES'],
    parentMotifId: 14,
  },
  192: {
    motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/MEDECIN_TRAITANT'],
    parentMotifId: 14,
  },
  194: {
    motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/RECHERCHE_SMR'],
    parentMotifId: 14,
  },
  77: { motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/SPECIALISTE'], parentMotifId: 14 },
  73: {
    motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/TRANSFERT_MANQUE_LIT'],
    parentMotifId: 14,
  },
  74: {
    motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/DELAIS_ATTENTE_PLACE_ETABLISSEMENT'],
    parentMotifId: 14,
  },
  75: { motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/AUTRES'], parentMotifId: 14 },
  76: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/REFUS_INTERVENTION_DOMICILE'] },
  // 123: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 124: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 125: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 126: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 127: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 128: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 129: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 130: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 131: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 132: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 133: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 134: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 135: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 136: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 137: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 138: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 139: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 140: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  141: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/GESTION_DECHETS_DASRI'] },
  // 142: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 143: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 144: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  // 145: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'], parentMotifId: 18 },
  202: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_CONDUITE_VEHICULE'], parentMotifId: 168 },
  200: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT'], parentMotifId: 168 },
  172: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/DEFAUT_GARDE'], parentMotifId: 168 },
  170: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/DEFAUT_OFFRE'], parentMotifId: 168 },
  204: {
    motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/NON_RESPECT_DISPOSITIONS_REGLEMENTAIRES'],
    parentMotifId: 168,
  },
  174: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/TRANSFERT_ENTRE_ETABLISSEMENTS'], parentMotifId: 168 },
  198: {
    motifIds: ['FACTURATIONS_HONORAIRES/PROBLEME_FACTURATION' /*, 'PROBLEMES_TRANSPORT_SANITAIRE/AUTRES'*/],
    parentMotifId: 168,
  },
  14: { motifIds: ['DIFFICULTE_RECHERCHE_ETABLISSEMENT_PROFESSIONNEL_SERVICE/AUTRES'] },
  17: { motifIds: ['FACTURATIONS_HONORAIRES/AUTRES'] },
  10: { motifIds: ['HOTELLERIE_LOCAUX_RESTAURATION/AUTRES'] },
  16: { motifIds: ['INFORMATIONS_DROITS_USAGERS/AUTRES'] },
  //11: { motifIds: ['PROBLEMES_ORGANISATION_RESSOURCES_HUMAINES/AUTRES'] },
  //158: { motifIds: ['MALTRAITANCE_PROFESSIONNELS_ENTOURAGE/AUTRES'] },
  // 168: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/AUTRES'] },
  15: { motifIds: ['MAUVAISE_ATTITUDE_PROFESSIONNELS/AUTRES'] },
  13: { motifIds: ['QUALITE_SOINS/ABSENCE_INSUFFISANCE_SOINS_PARAMEDICAUX'] },
  12: { motifIds: ['QUALITE_SOINS/AUTRES'] },
  // 18: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/AUTRES'] },
  19: { motifIds: ['ACTIVITES_ESTHETIQUE_NON_REGLEMENTEES/AUTRES'] },
  156: { motifIds: ['PROBLEMES_ENVIRONNEMENTAUX/SITUATION_EXCEPTIONNELLE'] },
  //176: { motifIds: ['PRATIQUE_NON_CONVENTIONNELLE/AUTRES'] },
  22: { motifIds: ['QUALITE_ACCOMPAGNEMENT_SERVICE/AUTRES'] },
  44: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_PRISE_EN_CHARGE_PATIENT'] },
  45: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/CONDITIONS_CONDUITE_VEHICULE'] },
  46: { motifIds: ['PROBLEMES_TRANSPORT_SANITAIRE/NON_RESPECT_DISPOSITIONS_REGLEMENTAIRES'] },
  121: {
    motifIds: ['FACTURATIONS_HONORAIRES/PROBLEME_FACTURATION' /*, 'PROBLEMES_TRANSPORT_SANITAIRE/AUTRES'*/],
  },
};

const logger = createDefaultLogger();
export function transcodeMotifIgas(idIgas: number): string[] {
  // TODO Retirer le || [] et le log.warn lorsque la correspondance aura été établie
  // Penser également à décommenter les 3 tests

  const motifIds = MOTIFS_IGAS_TRANSCO[idIgas]?.motifIds || [];
  if (motifIds.length === 0) {
    logger.warn(`Aucune correspondance SIRENA pour le motif IGAS id_igas=${idIgas}`);
  }
  // if (motifIds === undefined) {
  //   throw new SirecDataError(`Aucune correspondance SIRENA pour le motif IGAS id_igas=${idIgas}`);
  // }
  for (const motifId of motifIds) {
    if (motifLabelsById[motifId] === undefined) {
      throw new SirecDataError(
        `Le motif SIRENA "${motifId}" (id_igas=${idIgas}) n'a pas de libellé dans MOTIFS_HIERARCHICAL_DATA`,
      );
    }
  }
  return motifIds;
}

/**
 * Retourne l'id_igas du motif Igas parent, si ce motif en a un.
 * Utilisé pour ignorer un motif parent quand un de ses motifs enfants est aussi présent
 * (voir resolveMotifsIgas).
 */
export function getParentMotifIgasId(idIgas: number): number | undefined {
  return MOTIFS_IGAS_TRANSCO[idIgas]?.parentMotifId;
}
