import { REQUETE_PROVENANCE, type RequeteProvenance } from '@sirena/common/constants';
import { SirecTranscoError } from './sirecTransco.error.js';

const PROVENANCE_TRANSCO: Record<number, RequeteProvenance> = {
  26: REQUETE_PROVENANCE.PREMIER_MINISTRE,
  28: REQUETE_PROVENANCE.ELUS,
  30: REQUETE_PROVENANCE.MINISTERES,
  404: REQUETE_PROVENANCE.ASSURANCE_MALADIE,
  406: REQUETE_PROVENANCE.AUTRE,
  408: REQUETE_PROVENANCE.CONSEILS_ORDRE,
  410: REQUETE_PROVENANCE.CONSEIL_DEPARTEMENTAL,
  412: REQUETE_PROVENANCE.AUTRE,
  414: REQUETE_PROVENANCE.AUTRE,
  416: REQUETE_PROVENANCE.DEFENSEUR_DROITS,
  418: REQUETE_PROVENANCE.IGAS,
  420: REQUETE_PROVENANCE.MINISTERES,
  422: REQUETE_PROVENANCE.AUTRE,
  424: REQUETE_PROVENANCE.PREFECTURE,
  426: REQUETE_PROVENANCE.PRESIDENCE_REPUBLIQUE,
  428: REQUETE_PROVENANCE.PRESIDENCE_AN_SENAT,
  430: REQUETE_PROVENANCE.ASSOCIATIONS_USAGERS,
  432: REQUETE_PROVENANCE.AUTRE,
  434: REQUETE_PROVENANCE.AUTRE,
  436: REQUETE_PROVENANCE.AUTRE,
  804: REQUETE_PROVENANCE.DDETS_DREETS,
  806: REQUETE_PROVENANCE.DDETS_DREETS,
};

export function transcodeProvenance(idProvenance: number | null): RequeteProvenance | null {
  if (idProvenance === null) return null;
  const provenanceId = PROVENANCE_TRANSCO[idProvenance];
  if (provenanceId === undefined) throw new SirecTranscoError(idProvenance, 'provenance');
  return provenanceId;
}
