/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicMentionsLegalesRouteImport } from './routes/_public/mentions-legales'
import { Route as PublicGestionCookiesRouteImport } from './routes/_public/gestion-cookies'
import { Route as PublicDonneesPersonnellesRouteImport } from './routes/_public/donnees-personnelles'
import { Route as PublicAccessibiliteRouteImport } from './routes/_public/accessibilite'
import { Route as AuthInactiveRouteRouteImport } from './routes/_auth/inactive/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthUserRouteRouteImport } from './routes/_auth/_user/route'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthUserHomeRouteImport } from './routes/_auth/_user/home'
import { Route as AuthAdminUsersRouteRouteImport } from './routes/_auth/admin/users/route'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users/index'
import { Route as AuthAdminEntitesIndexRouteImport } from './routes/_auth/admin/entites/index'
import { Route as AuthAdminUsersAllRouteImport } from './routes/_auth/admin/users/all'
import { Route as AuthAdminUserUserIdRouteImport } from './routes/_auth/admin/user/$userId'
import { Route as AuthAdminEntitesEntiteIdRouteImport } from './routes/_auth/admin/entites/$entiteId'
import { Route as AuthUserRequestCreateRouteImport } from './routes/_auth/_user/request.create'
import { Route as AuthUserRequestRequestIdRouteImport } from './routes/_auth/_user/request.$requestId'
import { Route as AuthUserRequestCreateIndexRouteImport } from './routes/_auth/_user/request.create.index'
import { Route as AuthUserRequestRequestIdIndexRouteImport } from './routes/_auth/_user/request.$requestId.index'
import { Route as AuthUserRequestCreateSituationRouteImport } from './routes/_auth/_user/request.create.situation'
import { Route as AuthUserRequestCreatePersonneConcerneeRouteImport } from './routes/_auth/_user/request.create.personne-concernee'
import { Route as AuthUserRequestCreateDeclarantRouteImport } from './routes/_auth/_user/request.create.declarant'
import { Route as AuthUserRequestRequestIdSituationRouteImport } from './routes/_auth/_user/request.$requestId.situation'
import { Route as AuthUserRequestRequestIdProcessingRouteImport } from './routes/_auth/_user/request.$requestId/processing'
import { Route as AuthUserRequestRequestIdPersonneConcerneeRouteImport } from './routes/_auth/_user/request.$requestId.personne-concernee'
import { Route as AuthUserRequestRequestIdDeclarantRouteImport } from './routes/_auth/_user/request.$requestId.declarant'
import { Route as AuthUserRequestRequestIdSituationIndexRouteImport } from './routes/_auth/_user/request.$requestId.situation.index'
import { Route as AuthUserRequestRequestIdSituationSituationIdRouteImport } from './routes/_auth/_user/request.$requestId.situation.$situationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMentionsLegalesRoute = PublicMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicGestionCookiesRoute = PublicGestionCookiesRouteImport.update({
  id: '/gestion-cookies',
  path: '/gestion-cookies',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDonneesPersonnellesRoute =
  PublicDonneesPersonnellesRouteImport.update({
    id: '/donnees-personnelles',
    path: '/donnees-personnelles',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicAccessibiliteRoute = PublicAccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthInactiveRouteRoute = AuthInactiveRouteRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUserRouteRoute = AuthUserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthUserHomeRoute = AuthUserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthUserRouteRoute,
} as any)
const AuthAdminUsersRouteRoute = AuthAdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminEntitesIndexRoute = AuthAdminEntitesIndexRouteImport.update({
  id: '/entites/',
  path: '/entites/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminUsersAllRoute = AuthAdminUsersAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthAdminUsersRouteRoute,
} as any)
const AuthAdminUserUserIdRoute = AuthAdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminEntitesEntiteIdRoute =
  AuthAdminEntitesEntiteIdRouteImport.update({
    id: '/entites/$entiteId',
    path: '/entites/$entiteId',
    getParentRoute: () => AuthAdminRouteRoute,
  } as any)
const AuthUserRequestCreateRoute = AuthUserRequestCreateRouteImport.update({
  id: '/request/create',
  path: '/request/create',
  getParentRoute: () => AuthUserRouteRoute,
} as any)
const AuthUserRequestRequestIdRoute =
  AuthUserRequestRequestIdRouteImport.update({
    id: '/request/$requestId',
    path: '/request/$requestId',
    getParentRoute: () => AuthUserRouteRoute,
  } as any)
const AuthUserRequestCreateIndexRoute =
  AuthUserRequestCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthUserRequestCreateRoute,
  } as any)
const AuthUserRequestRequestIdIndexRoute =
  AuthUserRequestRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthUserRequestRequestIdRoute,
  } as any)
const AuthUserRequestCreateSituationRoute =
  AuthUserRequestCreateSituationRouteImport.update({
    id: '/situation',
    path: '/situation',
    getParentRoute: () => AuthUserRequestCreateRoute,
  } as any)
const AuthUserRequestCreatePersonneConcerneeRoute =
  AuthUserRequestCreatePersonneConcerneeRouteImport.update({
    id: '/personne-concernee',
    path: '/personne-concernee',
    getParentRoute: () => AuthUserRequestCreateRoute,
  } as any)
const AuthUserRequestCreateDeclarantRoute =
  AuthUserRequestCreateDeclarantRouteImport.update({
    id: '/declarant',
    path: '/declarant',
    getParentRoute: () => AuthUserRequestCreateRoute,
  } as any)
const AuthUserRequestRequestIdSituationRoute =
  AuthUserRequestRequestIdSituationRouteImport.update({
    id: '/situation',
    path: '/situation',
    getParentRoute: () => AuthUserRequestRequestIdRoute,
  } as any)
const AuthUserRequestRequestIdProcessingRoute =
  AuthUserRequestRequestIdProcessingRouteImport.update({
    id: '/processing',
    path: '/processing',
    getParentRoute: () => AuthUserRequestRequestIdRoute,
  } as any)
const AuthUserRequestRequestIdPersonneConcerneeRoute =
  AuthUserRequestRequestIdPersonneConcerneeRouteImport.update({
    id: '/personne-concernee',
    path: '/personne-concernee',
    getParentRoute: () => AuthUserRequestRequestIdRoute,
  } as any)
const AuthUserRequestRequestIdDeclarantRoute =
  AuthUserRequestRequestIdDeclarantRouteImport.update({
    id: '/declarant',
    path: '/declarant',
    getParentRoute: () => AuthUserRequestRequestIdRoute,
  } as any)
const AuthUserRequestRequestIdSituationIndexRoute =
  AuthUserRequestRequestIdSituationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthUserRequestRequestIdSituationRoute,
  } as any)
const AuthUserRequestRequestIdSituationSituationIdRoute =
  AuthUserRequestRequestIdSituationSituationIdRouteImport.update({
    id: '/$situationId',
    path: '/$situationId',
    getParentRoute: () => AuthUserRequestRequestIdSituationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/inactive': typeof AuthInactiveRouteRoute
  '/accessibilite': typeof PublicAccessibiliteRoute
  '/donnees-personnelles': typeof PublicDonneesPersonnellesRoute
  '/gestion-cookies': typeof PublicGestionCookiesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/home': typeof AuthUserHomeRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/request/$requestId': typeof AuthUserRequestRequestIdRouteWithChildren
  '/request/create': typeof AuthUserRequestCreateRouteWithChildren
  '/admin/entites/$entiteId': typeof AuthAdminEntitesEntiteIdRoute
  '/admin/user/$userId': typeof AuthAdminUserUserIdRoute
  '/admin/users/all': typeof AuthAdminUsersAllRoute
  '/admin/entites/': typeof AuthAdminEntitesIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
  '/request/$requestId/declarant': typeof AuthUserRequestRequestIdDeclarantRoute
  '/request/$requestId/personne-concernee': typeof AuthUserRequestRequestIdPersonneConcerneeRoute
  '/request/$requestId/processing': typeof AuthUserRequestRequestIdProcessingRoute
  '/request/$requestId/situation': typeof AuthUserRequestRequestIdSituationRouteWithChildren
  '/request/create/declarant': typeof AuthUserRequestCreateDeclarantRoute
  '/request/create/personne-concernee': typeof AuthUserRequestCreatePersonneConcerneeRoute
  '/request/create/situation': typeof AuthUserRequestCreateSituationRoute
  '/request/$requestId/': typeof AuthUserRequestRequestIdIndexRoute
  '/request/create/': typeof AuthUserRequestCreateIndexRoute
  '/request/$requestId/situation/$situationId': typeof AuthUserRequestRequestIdSituationSituationIdRoute
  '/request/$requestId/situation/': typeof AuthUserRequestRequestIdSituationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inactive': typeof AuthInactiveRouteRoute
  '/accessibilite': typeof PublicAccessibiliteRoute
  '/donnees-personnelles': typeof PublicDonneesPersonnellesRoute
  '/gestion-cookies': typeof PublicGestionCookiesRoute
  '/mentions-legales': typeof PublicMentionsLegalesRoute
  '/home': typeof AuthUserHomeRoute
  '/admin': typeof AuthAdminIndexRoute
  '/admin/entites/$entiteId': typeof AuthAdminEntitesEntiteIdRoute
  '/admin/user/$userId': typeof AuthAdminUserUserIdRoute
  '/admin/users/all': typeof AuthAdminUsersAllRoute
  '/admin/entites': typeof AuthAdminEntitesIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/request/$requestId/declarant': typeof AuthUserRequestRequestIdDeclarantRoute
  '/request/$requestId/personne-concernee': typeof AuthUserRequestRequestIdPersonneConcerneeRoute
  '/request/$requestId/processing': typeof AuthUserRequestRequestIdProcessingRoute
  '/request/create/declarant': typeof AuthUserRequestCreateDeclarantRoute
  '/request/create/personne-concernee': typeof AuthUserRequestCreatePersonneConcerneeRoute
  '/request/create/situation': typeof AuthUserRequestCreateSituationRoute
  '/request/$requestId': typeof AuthUserRequestRequestIdIndexRoute
  '/request/create': typeof AuthUserRequestCreateIndexRoute
  '/request/$requestId/situation/$situationId': typeof AuthUserRequestRequestIdSituationSituationIdRoute
  '/request/$requestId/situation': typeof AuthUserRequestRequestIdSituationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_user': typeof AuthUserRouteRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/inactive': typeof AuthInactiveRouteRoute
  '/_public/accessibilite': typeof PublicAccessibiliteRoute
  '/_public/donnees-personnelles': typeof PublicDonneesPersonnellesRoute
  '/_public/gestion-cookies': typeof PublicGestionCookiesRoute
  '/_public/mentions-legales': typeof PublicMentionsLegalesRoute
  '/_auth/admin/users': typeof AuthAdminUsersRouteRouteWithChildren
  '/_auth/_user/home': typeof AuthUserHomeRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/_user/request/$requestId': typeof AuthUserRequestRequestIdRouteWithChildren
  '/_auth/_user/request/create': typeof AuthUserRequestCreateRouteWithChildren
  '/_auth/admin/entites/$entiteId': typeof AuthAdminEntitesEntiteIdRoute
  '/_auth/admin/user/$userId': typeof AuthAdminUserUserIdRoute
  '/_auth/admin/users/all': typeof AuthAdminUsersAllRoute
  '/_auth/admin/entites/': typeof AuthAdminEntitesIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/_user/request/$requestId/declarant': typeof AuthUserRequestRequestIdDeclarantRoute
  '/_auth/_user/request/$requestId/personne-concernee': typeof AuthUserRequestRequestIdPersonneConcerneeRoute
  '/_auth/_user/request/$requestId/processing': typeof AuthUserRequestRequestIdProcessingRoute
  '/_auth/_user/request/$requestId/situation': typeof AuthUserRequestRequestIdSituationRouteWithChildren
  '/_auth/_user/request/create/declarant': typeof AuthUserRequestCreateDeclarantRoute
  '/_auth/_user/request/create/personne-concernee': typeof AuthUserRequestCreatePersonneConcerneeRoute
  '/_auth/_user/request/create/situation': typeof AuthUserRequestCreateSituationRoute
  '/_auth/_user/request/$requestId/': typeof AuthUserRequestRequestIdIndexRoute
  '/_auth/_user/request/create/': typeof AuthUserRequestCreateIndexRoute
  '/_auth/_user/request/$requestId/situation/$situationId': typeof AuthUserRequestRequestIdSituationSituationIdRoute
  '/_auth/_user/request/$requestId/situation/': typeof AuthUserRequestRequestIdSituationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/inactive'
    | '/accessibilite'
    | '/donnees-personnelles'
    | '/gestion-cookies'
    | '/mentions-legales'
    | '/admin/users'
    | '/home'
    | '/admin/'
    | '/request/$requestId'
    | '/request/create'
    | '/admin/entites/$entiteId'
    | '/admin/user/$userId'
    | '/admin/users/all'
    | '/admin/entites/'
    | '/admin/users/'
    | '/request/$requestId/declarant'
    | '/request/$requestId/personne-concernee'
    | '/request/$requestId/processing'
    | '/request/$requestId/situation'
    | '/request/create/declarant'
    | '/request/create/personne-concernee'
    | '/request/create/situation'
    | '/request/$requestId/'
    | '/request/create/'
    | '/request/$requestId/situation/$situationId'
    | '/request/$requestId/situation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/inactive'
    | '/accessibilite'
    | '/donnees-personnelles'
    | '/gestion-cookies'
    | '/mentions-legales'
    | '/home'
    | '/admin'
    | '/admin/entites/$entiteId'
    | '/admin/user/$userId'
    | '/admin/users/all'
    | '/admin/entites'
    | '/admin/users'
    | '/request/$requestId/declarant'
    | '/request/$requestId/personne-concernee'
    | '/request/$requestId/processing'
    | '/request/create/declarant'
    | '/request/create/personne-concernee'
    | '/request/create/situation'
    | '/request/$requestId'
    | '/request/create'
    | '/request/$requestId/situation/$situationId'
    | '/request/$requestId/situation'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/login'
    | '/_auth/_user'
    | '/_auth/admin'
    | '/_auth/inactive'
    | '/_public/accessibilite'
    | '/_public/donnees-personnelles'
    | '/_public/gestion-cookies'
    | '/_public/mentions-legales'
    | '/_auth/admin/users'
    | '/_auth/_user/home'
    | '/_auth/admin/'
    | '/_auth/_user/request/$requestId'
    | '/_auth/_user/request/create'
    | '/_auth/admin/entites/$entiteId'
    | '/_auth/admin/user/$userId'
    | '/_auth/admin/users/all'
    | '/_auth/admin/entites/'
    | '/_auth/admin/users/'
    | '/_auth/_user/request/$requestId/declarant'
    | '/_auth/_user/request/$requestId/personne-concernee'
    | '/_auth/_user/request/$requestId/processing'
    | '/_auth/_user/request/$requestId/situation'
    | '/_auth/_user/request/create/declarant'
    | '/_auth/_user/request/create/personne-concernee'
    | '/_auth/_user/request/create/situation'
    | '/_auth/_user/request/$requestId/'
    | '/_auth/_user/request/create/'
    | '/_auth/_user/request/$requestId/situation/$situationId'
    | '/_auth/_user/request/$requestId/situation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/mentions-legales': {
      id: '/_public/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof PublicMentionsLegalesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/gestion-cookies': {
      id: '/_public/gestion-cookies'
      path: '/gestion-cookies'
      fullPath: '/gestion-cookies'
      preLoaderRoute: typeof PublicGestionCookiesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/donnees-personnelles': {
      id: '/_public/donnees-personnelles'
      path: '/donnees-personnelles'
      fullPath: '/donnees-personnelles'
      preLoaderRoute: typeof PublicDonneesPersonnellesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/accessibilite': {
      id: '/_public/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof PublicAccessibiliteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/inactive': {
      id: '/_auth/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof AuthInactiveRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_user': {
      id: '/_auth/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthUserRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_user/home': {
      id: '/_auth/_user/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthUserHomeRouteImport
      parentRoute: typeof AuthUserRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/entites/': {
      id: '/_auth/admin/entites/'
      path: '/entites'
      fullPath: '/admin/entites/'
      preLoaderRoute: typeof AuthAdminEntitesIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/users/all': {
      id: '/_auth/admin/users/all'
      path: '/all'
      fullPath: '/admin/users/all'
      preLoaderRoute: typeof AuthAdminUsersAllRouteImport
      parentRoute: typeof AuthAdminUsersRouteRoute
    }
    '/_auth/admin/user/$userId': {
      id: '/_auth/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AuthAdminUserUserIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/entites/$entiteId': {
      id: '/_auth/admin/entites/$entiteId'
      path: '/entites/$entiteId'
      fullPath: '/admin/entites/$entiteId'
      preLoaderRoute: typeof AuthAdminEntitesEntiteIdRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/_user/request/create': {
      id: '/_auth/_user/request/create'
      path: '/request/create'
      fullPath: '/request/create'
      preLoaderRoute: typeof AuthUserRequestCreateRouteImport
      parentRoute: typeof AuthUserRouteRoute
    }
    '/_auth/_user/request/$requestId': {
      id: '/_auth/_user/request/$requestId'
      path: '/request/$requestId'
      fullPath: '/request/$requestId'
      preLoaderRoute: typeof AuthUserRequestRequestIdRouteImport
      parentRoute: typeof AuthUserRouteRoute
    }
    '/_auth/_user/request/create/': {
      id: '/_auth/_user/request/create/'
      path: '/'
      fullPath: '/request/create/'
      preLoaderRoute: typeof AuthUserRequestCreateIndexRouteImport
      parentRoute: typeof AuthUserRequestCreateRoute
    }
    '/_auth/_user/request/$requestId/': {
      id: '/_auth/_user/request/$requestId/'
      path: '/'
      fullPath: '/request/$requestId/'
      preLoaderRoute: typeof AuthUserRequestRequestIdIndexRouteImport
      parentRoute: typeof AuthUserRequestRequestIdRoute
    }
    '/_auth/_user/request/create/situation': {
      id: '/_auth/_user/request/create/situation'
      path: '/situation'
      fullPath: '/request/create/situation'
      preLoaderRoute: typeof AuthUserRequestCreateSituationRouteImport
      parentRoute: typeof AuthUserRequestCreateRoute
    }
    '/_auth/_user/request/create/personne-concernee': {
      id: '/_auth/_user/request/create/personne-concernee'
      path: '/personne-concernee'
      fullPath: '/request/create/personne-concernee'
      preLoaderRoute: typeof AuthUserRequestCreatePersonneConcerneeRouteImport
      parentRoute: typeof AuthUserRequestCreateRoute
    }
    '/_auth/_user/request/create/declarant': {
      id: '/_auth/_user/request/create/declarant'
      path: '/declarant'
      fullPath: '/request/create/declarant'
      preLoaderRoute: typeof AuthUserRequestCreateDeclarantRouteImport
      parentRoute: typeof AuthUserRequestCreateRoute
    }
    '/_auth/_user/request/$requestId/situation': {
      id: '/_auth/_user/request/$requestId/situation'
      path: '/situation'
      fullPath: '/request/$requestId/situation'
      preLoaderRoute: typeof AuthUserRequestRequestIdSituationRouteImport
      parentRoute: typeof AuthUserRequestRequestIdRoute
    }
    '/_auth/_user/request/$requestId/processing': {
      id: '/_auth/_user/request/$requestId/processing'
      path: '/processing'
      fullPath: '/request/$requestId/processing'
      preLoaderRoute: typeof AuthUserRequestRequestIdProcessingRouteImport
      parentRoute: typeof AuthUserRequestRequestIdRoute
    }
    '/_auth/_user/request/$requestId/personne-concernee': {
      id: '/_auth/_user/request/$requestId/personne-concernee'
      path: '/personne-concernee'
      fullPath: '/request/$requestId/personne-concernee'
      preLoaderRoute: typeof AuthUserRequestRequestIdPersonneConcerneeRouteImport
      parentRoute: typeof AuthUserRequestRequestIdRoute
    }
    '/_auth/_user/request/$requestId/declarant': {
      id: '/_auth/_user/request/$requestId/declarant'
      path: '/declarant'
      fullPath: '/request/$requestId/declarant'
      preLoaderRoute: typeof AuthUserRequestRequestIdDeclarantRouteImport
      parentRoute: typeof AuthUserRequestRequestIdRoute
    }
    '/_auth/_user/request/$requestId/situation/': {
      id: '/_auth/_user/request/$requestId/situation/'
      path: '/'
      fullPath: '/request/$requestId/situation/'
      preLoaderRoute: typeof AuthUserRequestRequestIdSituationIndexRouteImport
      parentRoute: typeof AuthUserRequestRequestIdSituationRoute
    }
    '/_auth/_user/request/$requestId/situation/$situationId': {
      id: '/_auth/_user/request/$requestId/situation/$situationId'
      path: '/$situationId'
      fullPath: '/request/$requestId/situation/$situationId'
      preLoaderRoute: typeof AuthUserRequestRequestIdSituationSituationIdRouteImport
      parentRoute: typeof AuthUserRequestRequestIdSituationRoute
    }
  }
}

interface AuthUserRequestRequestIdSituationRouteChildren {
  AuthUserRequestRequestIdSituationSituationIdRoute: typeof AuthUserRequestRequestIdSituationSituationIdRoute
  AuthUserRequestRequestIdSituationIndexRoute: typeof AuthUserRequestRequestIdSituationIndexRoute
}

const AuthUserRequestRequestIdSituationRouteChildren: AuthUserRequestRequestIdSituationRouteChildren =
  {
    AuthUserRequestRequestIdSituationSituationIdRoute:
      AuthUserRequestRequestIdSituationSituationIdRoute,
    AuthUserRequestRequestIdSituationIndexRoute:
      AuthUserRequestRequestIdSituationIndexRoute,
  }

const AuthUserRequestRequestIdSituationRouteWithChildren =
  AuthUserRequestRequestIdSituationRoute._addFileChildren(
    AuthUserRequestRequestIdSituationRouteChildren,
  )

interface AuthUserRequestRequestIdRouteChildren {
  AuthUserRequestRequestIdDeclarantRoute: typeof AuthUserRequestRequestIdDeclarantRoute
  AuthUserRequestRequestIdPersonneConcerneeRoute: typeof AuthUserRequestRequestIdPersonneConcerneeRoute
  AuthUserRequestRequestIdProcessingRoute: typeof AuthUserRequestRequestIdProcessingRoute
  AuthUserRequestRequestIdSituationRoute: typeof AuthUserRequestRequestIdSituationRouteWithChildren
  AuthUserRequestRequestIdIndexRoute: typeof AuthUserRequestRequestIdIndexRoute
}

const AuthUserRequestRequestIdRouteChildren: AuthUserRequestRequestIdRouteChildren =
  {
    AuthUserRequestRequestIdDeclarantRoute:
      AuthUserRequestRequestIdDeclarantRoute,
    AuthUserRequestRequestIdPersonneConcerneeRoute:
      AuthUserRequestRequestIdPersonneConcerneeRoute,
    AuthUserRequestRequestIdProcessingRoute:
      AuthUserRequestRequestIdProcessingRoute,
    AuthUserRequestRequestIdSituationRoute:
      AuthUserRequestRequestIdSituationRouteWithChildren,
    AuthUserRequestRequestIdIndexRoute: AuthUserRequestRequestIdIndexRoute,
  }

const AuthUserRequestRequestIdRouteWithChildren =
  AuthUserRequestRequestIdRoute._addFileChildren(
    AuthUserRequestRequestIdRouteChildren,
  )

interface AuthUserRequestCreateRouteChildren {
  AuthUserRequestCreateDeclarantRoute: typeof AuthUserRequestCreateDeclarantRoute
  AuthUserRequestCreatePersonneConcerneeRoute: typeof AuthUserRequestCreatePersonneConcerneeRoute
  AuthUserRequestCreateSituationRoute: typeof AuthUserRequestCreateSituationRoute
  AuthUserRequestCreateIndexRoute: typeof AuthUserRequestCreateIndexRoute
}

const AuthUserRequestCreateRouteChildren: AuthUserRequestCreateRouteChildren = {
  AuthUserRequestCreateDeclarantRoute: AuthUserRequestCreateDeclarantRoute,
  AuthUserRequestCreatePersonneConcerneeRoute:
    AuthUserRequestCreatePersonneConcerneeRoute,
  AuthUserRequestCreateSituationRoute: AuthUserRequestCreateSituationRoute,
  AuthUserRequestCreateIndexRoute: AuthUserRequestCreateIndexRoute,
}

const AuthUserRequestCreateRouteWithChildren =
  AuthUserRequestCreateRoute._addFileChildren(
    AuthUserRequestCreateRouteChildren,
  )

interface AuthUserRouteRouteChildren {
  AuthUserHomeRoute: typeof AuthUserHomeRoute
  AuthUserRequestRequestIdRoute: typeof AuthUserRequestRequestIdRouteWithChildren
  AuthUserRequestCreateRoute: typeof AuthUserRequestCreateRouteWithChildren
}

const AuthUserRouteRouteChildren: AuthUserRouteRouteChildren = {
  AuthUserHomeRoute: AuthUserHomeRoute,
  AuthUserRequestRequestIdRoute: AuthUserRequestRequestIdRouteWithChildren,
  AuthUserRequestCreateRoute: AuthUserRequestCreateRouteWithChildren,
}

const AuthUserRouteRouteWithChildren = AuthUserRouteRoute._addFileChildren(
  AuthUserRouteRouteChildren,
)

interface AuthAdminUsersRouteRouteChildren {
  AuthAdminUsersAllRoute: typeof AuthAdminUsersAllRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminUsersRouteRouteChildren: AuthAdminUsersRouteRouteChildren = {
  AuthAdminUsersAllRoute: AuthAdminUsersAllRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminUsersRouteRouteWithChildren =
  AuthAdminUsersRouteRoute._addFileChildren(AuthAdminUsersRouteRouteChildren)

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersRouteRoute: typeof AuthAdminUsersRouteRouteWithChildren
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminEntitesEntiteIdRoute: typeof AuthAdminEntitesEntiteIdRoute
  AuthAdminUserUserIdRoute: typeof AuthAdminUserUserIdRoute
  AuthAdminEntitesIndexRoute: typeof AuthAdminEntitesIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersRouteRoute: AuthAdminUsersRouteRouteWithChildren,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminEntitesEntiteIdRoute: AuthAdminEntitesEntiteIdRoute,
  AuthAdminUserUserIdRoute: AuthAdminUserUserIdRoute,
  AuthAdminEntitesIndexRoute: AuthAdminEntitesIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthUserRouteRoute: typeof AuthUserRouteRouteWithChildren
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthInactiveRouteRoute: typeof AuthInactiveRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthUserRouteRoute: AuthUserRouteRouteWithChildren,
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthInactiveRouteRoute: AuthInactiveRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAccessibiliteRoute: typeof PublicAccessibiliteRoute
  PublicDonneesPersonnellesRoute: typeof PublicDonneesPersonnellesRoute
  PublicGestionCookiesRoute: typeof PublicGestionCookiesRoute
  PublicMentionsLegalesRoute: typeof PublicMentionsLegalesRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAccessibiliteRoute: PublicAccessibiliteRoute,
  PublicDonneesPersonnellesRoute: PublicDonneesPersonnellesRoute,
  PublicGestionCookiesRoute: PublicGestionCookiesRoute,
  PublicMentionsLegalesRoute: PublicMentionsLegalesRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
