name: Feature branches - build

on:
  push:
    branches-ignore:
      - main
      - validation
      - production
      # branch use to deploy on test env
      - chore/deploy

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-workflows/build-and-deploy.yml
    with:
      deploy: false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 