name: Build and deploy

on:
  push:
    branches:
      - main
      - validation

env:
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'integration' || 'validation' }}

jobs:
  build-docker:
    name: Build docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Compute version
        id: version
        run: echo "value=${{ env.ENVIRONMENT }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: ./.github/actions/build-docker
        with:
          version: ${{ steps.version.outputs.value }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          environment: ${{ env.ENVIRONMENT }}

    outputs:
      version: ${{ steps.version.outputs.value }}

  deploy:
    name: Deploy to ${{ needs.build-docker.outputs.version }}
    needs: build-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - name: Deploy to GitOps
        uses: ./.github/actions/deploy-gitops
        with:
          environment: ${{ env.ENVIRONMENT }}
          version: ${{ needs.build-docker.outputs.version }}
          gitops-repo-key: ${{ secrets.GITOPS_REPO_KEY }}
          helm-repo-pat: ${{ secrets.HELM_REPO_PAT }}

  e2e-tests:
    name: End-to-End Tests
    if: github.ref_name == 'main'
    needs: [build-docker, deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      BASE_URL: https://sirena.${{ github.ref_name == 'main' && 'integration' || 'validation' }}.dev.atlas.fabrique.social.gouv.fr

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6

      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "22"
          cache: "pnpm"

      # TODO: revert pnpm audit when fixed (https://github.com/pnpm/pnpm/issues/11265)
      # - name: Audit dependencies
      #   run: |
      #     cd apps/frontend
      #     pnpm audit --audit-level=moderate
      - name: Install dependencies
        run: |
          cd apps/frontend
          pnpm install

      - name: Install Playwright Browsers
        run: |
          cd apps/frontend
          npx playwright install --with-deps chromium

      - name: Wait for deployment
        run: |
          cd apps/frontend
          npx tsx tests/ci/wait-for-deployment.ts
        env:
          EXPECTED_VERSION: ${{ needs.build-docker.outputs.version }}
          BACKEND_URL: ${{ env.BASE_URL }}/api
          FRONTEND_URL: ${{ env.BASE_URL }}

      - name: Run Playwright tests
        run: |
          cd apps/frontend
          pnpm run test:e2e
        env:
          FRONTEND_URI: ${{ env.BASE_URL }}
          E2E_CI: true
          E2E_ENTITY_ADMIN_USER_1_EMAIL: ${{ vars.TEST_USER_EMAIL }}
          E2E_ENTITY_ADMIN_USER_1_PASSWORD: ${{ vars.TEST_USER_PASSWORD }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v5
        if: always()
        continue-on-error: true
        with:
          name: playwright-report
          path: apps/frontend/playwright-report/
          retention-days: 1
