name: Build docker images

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" | tee -a "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.SHORT_SHA }}
            
      - name: Save image tag in an env var
        run: |
          echo "IMAGE_TAG=${{ steps.meta.outputs.tags }}" | tee -a $GITHUB_ENV

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}-backend
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}-frontend
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_IS_LOGGED_TOKEN_NAME=is_logged_token
