name: Run CI
run-name: Run CI

on:
  push:
    branches: ['chore/deploy']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITOPS_REPO: fabrique-atlas/org-sdpsn-ws-ptt
  
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" | tee -a "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-backend

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-frontend

      - name: Install dependencies
        working-directory: ./deploy
        run: |
          npm install
      
      - name: Check format and lint
        working-directory: ./deploy
        run: |
          npm run lint

      - name: Render manifests
        working-directory: ./deploy
        run: |
          npm run build

      # - name: Checkout GitOps repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ env.GITOPS_REPO }}
      #     path: gitops-repo
      #     ssh-key: ${{ secrets.GITOPS_REPO_KEY }}

      # - run: |
      #     rm -f gitops-repo/deployment-targets/developpement/*.yaml
      #     rm -rf gitops-repo/deployment-targets/developpement/home/*
      #     cp -r deploy/dist/developpement/* gitops-repo/deployment-targets/developpement/home/
      #     cp gitops-repo/deployment-targets/developpement/home/* gitops-repo/deployment-targets/developpement
      #     cp gitops-repo/deployment-targets/developpement/chantier/* gitops-repo/deployment-targets/developpement
      #     cp gitops-repo/deployment-targets/developpement/lsp/* gitops-repo/deployment-targets/developpement

      #     # rm -f gitops-repo/deployment-targets/dev/*.yaml
      #     # rm -rf gitops-repo/deployment-targets/dev/home/*
      #     # cp -r deploy/dist/dev/* gitops-repo/deployment-targets/dev/home/
      #     # cp gitops-repo/deployment-targets/dev/home/* gitops-repo/deployment-targets/dev
      #     # cp gitops-repo/deployment-targets/dev/chantier/* gitops-repo/deployment-targets/dev
      #     # cp gitops-repo/deployment-targets/dev/lsp/* gitops-repo/deployment-targets/dev

      #     # mail standard bot github Actions
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     cd gitops-repo
      #     git add .
      #     git commit -m 'Déploiement manifestes home environnement "developpement"'
      #     git push
