name: Lint and Unit Tests

on:
  push:

permissions:
  contents: read

jobs:
  lint-and-build:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    env:
      PG_URL: postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6
      - name: Use Node.js 22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: "pnpm"
      # TODO: revert pnpm audit when fixed (https://github.com/pnpm/pnpm/issues/11265)
      # - name: Audit dependencies
      #   run: pnpm audit --audit-level=moderate
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm lint
      - name: Run gitLeaks
        run: pnpm gitleaks:ci
      - name: Build common
        run: pnpm build:common
      - name: Build backend-utils
        run: pnpm build:backend-utils
      - name: Generate types
        run: pnpm db:generate
      - name: build db
        run: pnpm build:db
      - name: Build backend
        run: pnpm build:backend
      - name: Run tests
        run: pnpm test:unit
